// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.
// Reference: https://github.com/helmforgedev/charts/blob/main/charts/wallabag/values.yaml
@if(!debug)

package main

// Defaults
values: {
	nameOverride: ""
	fullnameOverride: ""
	commonLabels: {}
	replicaCount: 1
	
	image: {
		repository: "docker.io/wallabag/wallabag"
		tag:        "2.6.14"
		pullPolicy: "IfNotPresent"
	}
	imagePullSecrets: []

	wallabag: {
		port:              80
		domainName:        "http://localhost:8080"
		secret:            ""
		existingSecret:    ""
		existingSecretKey: "symfony-secret"
		registration:      false
		extraEnv: []
		adminUser: {
			username: "wallabag"
			email:    "admin@example.com"
			password: "changeit"
		}
	}

	database: {
		external: {
			host:                      ""
			port:                      "5432"
			name:                      "wallabag"
			username:                  "wallabag"
			password:                  ""
			existingSecret:            ""
			existingSecretPasswordKey: "password"
		}
	}

	externalRedis: {
		host: ""
		port: "6379"
	}

	persistence: {
		enabled:       true
		size:          "2Gi"
		storageClass:  ""
		accessModes: ["ReadWriteOnce"]
		existingClaim: ""
	}

	serviceAccount: {
		create:      true
		name:        ""
		annotations: {}
	}

	service: {
		type:        "ClusterIP"
		port:        80
		annotations: {}
	}


	probes: {
		startup: {
			enabled:             true
			initialDelaySeconds: 15
			periodSeconds:       10
			timeoutSeconds:      5
			failureThreshold:    30
		}
		liveness: {
			enabled:             true
			initialDelaySeconds: 0
			periodSeconds:       15
			timeoutSeconds:      5
			failureThreshold:    3
		}
		readiness: {
			enabled:             true
			initialDelaySeconds: 0
			periodSeconds:       10
			timeoutSeconds:      5
			failureThreshold:    3
		}
	}

	resources: {
		requests: {
			cpu:    "100m"
			memory: "128Mi"
		}
		limits: {
			cpu:    "500m"
			memory: "512Mi"
		}
	}
	podSecurityContext: {
		runAsUser:    65510
		runAsGroup:   65510
		runAsNonRoot: true
		fsGroup:      65510
		seccompProfile: {
			type: "RuntimeDefault"
		}
	}
	 securityContext: {
		allowPrivilegeEscalation: false
		capabilities: {
			drop: ["ALL"]
			add: ["NET_BIND_SERVICE"]
		}
    }

	backup: {
		enabled:                    false
		schedule:                   "0 3 * * *"
		suspend:                    false
		concurrencyPolicy:          "Forbid"
		successfulJobsHistoryLimit: 3
		failedJobsHistoryLimit:     3
		backoffLimit:               1
		archivePrefix:              "wallabag"
		images: {
			postgresql: "docker.io/library/postgres:18-alpine"
			uploader:   "docker.io/helmforge/mc:1.0.0"
		}
		resources: {}
		s3: {
			endpoint:                    ""
			bucket:                      ""
			prefix:                      "wallabag"
			createBucketIfNotExists:     true
			existingSecret:              ""
			existingSecretAccessKeyKey:  "access-key"
			existingSecretSecretKeyKey:  "secret-key"
			accessKey:                   ""
			secretKey:                   ""
		}
		database: {
			host:                      ""
			port:                      ""
			name:                      ""
			username:                  ""
			password:                  ""
			existingSecret:            ""
			existingSecretPasswordKey: "password"
			postgresDumpArgs:          ""
		}
	}

	nodeSelector: {}
	tolerations: []
	affinity: {}
	topologySpreadConstraints: []
	priorityClassName:             ""
	terminationGracePeriodSeconds: 30
	podLabels: {}
	podAnnotations: {}
	extraVolumes: []
	extraVolumeMounts: []
	extraManifests: []

	postgresql: {
		enabled:      true
		architecture: "standalone"
		auth: {
			database: "wallabag"
			username: "wallabag"
			password: "change-me-please-db-password!"
		}
		image: {
			repository: "docker.io/library/postgres"
			tag:        "18.4-trixie"
			pullPolicy: "IfNotPresent"
			digest:     ""
		}
		resources: {
			requests: {
				cpu:    "100m"
				memory: "256Mi"
			}
			limits: {
				cpu:    "500m"
				memory: "512Mi"
			}
		}
		persistence: {
			enabled:      true
			size:         "8Gi"
			storageClass: ""
		}
		podSecurityContext: {
			runAsUser:    65510
			runAsGroup:   65510
			runAsNonRoot: true
			fsGroup:      65510
			seccompProfile: {
				type: "RuntimeDefault"
			}
		}
		securityContext: {
			allowPrivilegeEscalation: false
			capabilities: {
				drop: ["ALL"]
			}
			runAsUser:    65510
			runAsGroup:   65510
			runAsNonRoot: true
		}
	}

	redis: {
		enabled:      true
		architecture: "standalone"
		auth: {
			password: ""
		}
		image: {
			repository: "docker.io/library/redis"
			tag:        "8.10.0"
			pullPolicy: "IfNotPresent"
			digest:     ""
		}
		resources: {
			requests: {
				cpu:    "50m"
				memory: "64Mi"
			}
			limits: {
				cpu:    "200m"
				memory: "128Mi"
			}
		}
		persistence: {
			enabled:      true
			size:         "8Gi"
			storageClass: ""
		}
		podSecurityContext: {
			runAsUser:    65510
			runAsGroup:   65510
			runAsNonRoot: true
			fsGroup:      65510
			seccompProfile: {
				type: "RuntimeDefault"
			}
		}
		securityContext: {
			allowPrivilegeEscalation: false
			capabilities: {
				drop: ["ALL"]
			}
			runAsUser:    65510
			runAsGroup:   65510
			runAsNonRoot: true
		}
	}
}
