// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.
// References: https://github.com/Egston/pimcore-k8s/blob/main/charts/pimcore/values.yaml https://docs.pimcore.com/platform/Paas/Environment_Variables_Reference/#build-phase-service-configuration-variables

@if(!debug)

package main

// Defaults matching Helm values.yaml
values: {
	replicaCount: 1

	nameOverride: ""
	fullnameOverride: ""

	pimcore: {
		tag: "main"
		appEnv: "prod"
		appSecret: "ChangeMe123!"
		instanceIdentifier: "pimcore-evocms-0.1"
		productKey: "eyJwYXlsb2FkIjoie1wiaWRcIjpcIjRlNDU1ZGY0YmU2YzI2NzlhNDhkYzE1M2VhNTZlYmZkNGMxZjVkZmNlY2UwYzRhZjc1NjI3MDkyZWE5YWZjOWFcIixcInRpbWVzdGFtcFwiOjE3ODUyNDk1ODZ9Iiwic2lnbmF0dXJlIjoiTUVZQ0lRRGViXC9lS2tkeUliem9jUUlQS1VaOEhEMkhUSksycXpyVXBEUytRNGIzODBnSWhBSzBnZWVhOWlvZTdGYmRtZlM2elh3XC82Mm9VcDNTcUtyYStWdStMT1VUMFkifQ=="
		encryptionSecret: "def00000acb380da2a08598936351dd70af63d1b6867b5eb6edbe955a9ff0a5e2189265b8c0a1efa056abffa277b50fe02977c7e49ef9942b17df2ee2ab0abb66ca7f469"
		redisServer: "redis-master.pimcore.svc.cluster.local"
		redisPassword: "ChangeMe123!"
		createProject: "pimcore/skeleton"
		username: "admin"
		password: "ChangeMe123!"
		db: {
			name: "pimcore"
			root_password: "root"
			host: "mysql-mariadb.pimcore.svc.cluster.local"
			port: 3306
			username: "pimcore"
			password: "ChangeMe123!"
		}
		customConfigFiles: {
			"config-yaml": {
				enabled:       false
				localPath:     "pimcore-config/skeleton/config.yaml"
				containerPath: "config/config.yaml"
			}
			"bundles-php": {
				enabled:       false
				localPath:     "pimcore-config/skeleton/bundles.php"
				containerPath: "config/bundles.php"
			}
		}
		mountedConfigDirs: {}
		customEnvVars: []
		redisAuthCheck: {
			enabled: true
			maxAttempts: 24
			retryDelaySeconds: 5
		}
	}


	php: {
		imagePullSecrets: []
		image: {
			registry: "pimcore/pimcore"
			tag: "php8.5-latest"
			pullPolicy: "Always"
		}
		replicas: 1
		pdb: {
			enabled: true
		}
		strategy: {}
		topologySpreadConstraints: []
		podAnnotations: {}
		service: {
			type: "ClusterIP"
			port: 9000
		}
		phpUser: {
			userName: "www-data"
			uid: 33
			groupName: "www-data"
			gid: 33
		}
		fpmPool: {
			pm: "dynamic"
			pmMaxChildren: 100
			pmStartServers: 3
			pmMinSpareServers: 3
			pmMaxSpareServers: 8
			pmMaxRequests: 10000
			pmProcessIdleTimeout: "10s"
		}
		resources: {
			requests: {
				cpu: "500m"
				memory: "1Gi"
				"ephemeral-storage": "5Gi"
			}
			limits: {
				cpu: "1000m"
				memory: "2Gi"
				"ephemeral-storage": "5Gi"
			}
		}
		startupProbe: {
			enabled: true
			exec: {
				command: [
					"sh",
					"-c",
					"SCRIPT_NAME=/fpm-ping SCRIPT_FILENAME=/fpm-ping REQUEST_METHOD=GET cgi-fcgi -bind -connect 127.0.0.1:9000 | grep -qx pong",
				]
			}
			periodSeconds: 10
			timeoutSeconds: 5
			failureThreshold: 30
		}
		livenessProbe: {
			enabled: true
			exec: {
				command: [
					"sh",
					"-c",
					"SCRIPT_NAME=/fpm-ping SCRIPT_FILENAME=/fpm-ping REQUEST_METHOD=GET cgi-fcgi -bind -connect 127.0.0.1:9000 | grep -qx pong",
				]
			}
			periodSeconds: 30
			timeoutSeconds: 5
			failureThreshold: 3
		}
		readinessProbe: {
			enabled: false
			tcpSocket: {
				port: 9000
			}
			initialDelaySeconds: 10
			periodSeconds: 10
			timeoutSeconds: 3
			failureThreshold: 3
		}
		ini: {
			pimcore: {
				phpMemoryLimit: "512M"
				phpMaxExecutionTime: 300
				phpErrorReporting: "E_ALL"
				phpDisplayErrors: "Off"
				phpDisplayStartupErrors: 1
				phpPostMaxSize: "100M"
				phpUploadMaxFilesize: "100M"
				opcacheEnable: 1
				opcacheEnableCli: 0
				opcacheMemoryConsumption: 512
				opcacheMaxAcceleratedFiles: 10000
				opcacheValidateTimestamps: 1
				opcacheConsistencyChecks: 0
			}
			maintenance: {
				cronjob: {
					phpMemoryLimit: "512M"
					phpMaxExecutionTime: 0
				}
				worker: {
					phpMemoryLimit: "512M"
					phpMaxExecutionTime: 0
				}
				shell: {
					phpMemoryLimit: "0"
					phpMaxExecutionTime: 0
				}
			}
			installation: {
				phpMemoryLimit: "512M"
				phpMaxExecutionTime: 0
			}
		}
	}

	nginx: {
		imagePullSecrets: []
		image: {
			registry: "nginx"
			tag: "stable-alpine"
			pullPolicy: "IfNotPresent"
		}
		config: ""


		compression: {
			enabled: true
			gzip: {
				enabled: true
				min_length: 1
				comp_level: 1
				types: "text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript"
			}
			brotli: {
				enabled: false
				comp_level: 6
				types: "text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript"
			}
		}
		replicas: 1
		pdb: {
			enabled: true
		}
		strategy: {}
		topologySpreadConstraints: []
		podAnnotations: {}
		tag: "master"
		service: {
			type: "ClusterIP"
			port: 80
		}
		annotations: {
			"cloud.google.com/neg": "{\"ingress\": true}"
		}
		backendConfig: {
			enabled: false
			timeoutSec: 300
			healthCheck: {
				checkIntervalSec: 30
				timeoutSec: 30
				healthyThreshold: 2
				unhealthyThreshold: 2
				requestPath: "/livez"
				type: "HTTP"
				port: 80
			}
		}
		resources: {
			requests: {
				cpu: "100m"
				memory: "64Mi"
				"ephemeral-storage": "256Mi"
			}
			limits: {
				cpu: "200m"
				memory: "128Mi"
				"ephemeral-storage": "256Mi"
			}
		}
		clientMaxBodySize: "100m"
		cacheControl: {
			assets: "public, max-age=300, must-revalidate"
			thumbnails: "public, max-age=300, must-revalidate"
		}
		sharedFolders: ["public", "vendor"]
		startupProbe: {
			enabled: true
			httpGet: {
				path: "/livez"
				port: 80
			}
			periodSeconds: 5
			timeoutSeconds: 3
			failureThreshold: 60
		}
		livenessProbe: {
			enabled: true
			httpGet: {
				path: "/livez"
				port: 80
			}
			periodSeconds: 30
			timeoutSeconds: 3
			failureThreshold: 3
		}
		readinessProbe: {
			enabled: false
			httpGet: {
				path: "/readyz"
				port: 80
			}
			initialDelaySeconds: 2
			periodSeconds: 10
			timeoutSeconds: 5
			failureThreshold: 3
		}
	}

	installation: {
		resources: {
			requests: {
				cpu: "250m"
				memory: "512Mi"
				"ephemeral-storage": "1Gi"
			}
			limits: {
				cpu: "500m"
				memory: "1Gi"
				"ephemeral-storage": "1Gi"
			}
		}
	}

	maintenance: {
		cronjob: {
			resources: {
				requests: {
					cpu: "100m"
					memory: "256Mi"
					"ephemeral-storage": "3Gi"
				}
				limits: {
					cpu: "200m"
					memory: "512Mi"
					"ephemeral-storage": "3Gi"
				}
			}
		}
		worker: {
			replicas: 1
			extraTransports: []
			messengerMemoryLimit: ""
			customEnvVars: []
			resources: {
				requests: {
					cpu: "100m"
					memory: "256Mi"
					"ephemeral-storage": "3Gi"
				}
				limits: {
					cpu: "200m"
					memory: "512Mi"
					"ephemeral-storage": "3Gi"
				}
			}
			livenessProbe: {
				enabled: true
				exec: {
					command: [
						"sh",
						"-c",
						"pgrep -f messenger:consume >/dev/null",
					]
				}
				initialDelaySeconds: 60
				periodSeconds: 60
				timeoutSeconds: 5
				failureThreshold: 3
			}
		}
		shell: {
			replicas: 0
			resources: {
				requests: {
					cpu: "100m"
					memory: "256Mi"
					"ephemeral-storage": "3Gi"
				}
				limits: {
					cpu: "200m"
					memory: "512Mi"
					"ephemeral-storage": "3Gi"
				}
			}
			maintainer: {
				userName: "maintainer"
				userId: 1000
				groupName: "developers"
				groupId: 1200
			}
			installPackages: "ranger vim procps"
			entrypointAdditionalCommands: """
				apt-get install -y git
				su - maintainer -c "
				  git config --global --add safe.directory /var/www/pimcore;
				  git config --global user.name 'Pimcore Maintainer';
				  git config --global user.email 'maintainer@example.com';
				"
				"""
			extraVolumeMounts: []
		}
		consoleCronjobs: {}
		mysqlBackup: {
			enabled: false
			imagePullSecrets: []
			image: {
				registry: "mariadb"
				tag: "11.4"
				pullPolicy: "Always"
			}
			compression: {
				tool: "pigz"
			}
			replicas: 1
			resources: {
				requests: {
					cpu: "100m"
					memory: "128Mi"
					"ephemeral-storage": "2Gi"
				}
				limits: {
					cpu: "200m"
					memory: "256Mi"
					"ephemeral-storage": "2Gi"
				}
			}
		}
	}

	pvc: {
		data: {
			existingClaim: ""
			subPath: "pimcore"
			sharedSubPaths: {}
			name: "data"
			storage: "10Gi"
			accessMode: "ReadWriteOnce"
			storageClass: ""
			initFromRepo: {
				enabled: false
				gitRepositoryUrl: "ChangeMe123!"
				gitUserName: "git"
				gitPersonalAccessToken: ""
			}
			composerAuth: ""
			gitExtraHeader: {
				host: ""
				value: ""
			}
		}
		mysqlBackup: {
			existingClaim: ""
			subPath: "pimcore-mysql-backup"
			name: "mysql-backup"
			storage: "10Gi"
			accessMode: "ReadWriteOnce"
			storageClass: ""
		}
		mysql: {
			existingClaim: ""
			subPath: "mysql"
			name: "mysql"
			storage: "8Gi"
			accessMode: "ReadWriteOnce"
			storageClass: ""
		}
		redis: {
			existingClaim: ""
			subPath: "redis"
			name: "redis"
			storage: "8Gi"
			accessMode: "ReadWriteOnce"
			storageClass: ""
		}
		opensearch: {
			existingClaim: ""
			subPath: "opensearch"
			name: "opensearch"
			storage: "5Gi"
			accessMode: "ReadWriteOnce"
			storageClass: ""
		}
		rabbitmq: {
			existingClaim: ""
			subPath: "rabbitmq"
			name: "rabbitmq"
			storage: "5Gi"
			accessMode: "ReadWriteOnce"
			storageClass: ""
		}
	}

	mysql: {
		replicas: 1
		image: {
			registry: "mariadb"
			tag: "11.4"
			pullPolicy: "Always"
		}
		pdb: {
			enabled: true
		}
		primary: {
			containerPorts: mysql: 3306
			configuration: """
				[mysqld]
				skip-name-resolve
				explicit_defaults_for_timestamp
				basedir=/opt/bitnami/mariadb
				datadir=/bitnami/mariadb/data
				plugin_dir=/opt/bitnami/mariadb/plugin
				port=3306
				socket=/opt/bitnami/mariadb/tmp/mysql.sock
				tmpdir=/opt/bitnami/mariadb/tmp
				max_allowed_packet=256M
				bind-address=0.0.0.0
				pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
				log-error=/opt/bitnami/mariadb/logs/mysqld.log
				character-set-server=utf8mb4
				collation-server=utf8mb4_unicode_ci
				slow_query_log=0
				long_query_time=10.0
				connect_timeout=30
				"""
		}
		auth: {
			database:        "pimcore"
			username:        "pimcore"
			replicationUser: "replicator"
		}
		resources: {
			requests: {
				cpu: "250m"
				memory: "256Mi"
			}
			limits: {
				cpu: "1000m"
				memory: "1Gi"
			}
		}
	}

	redis: {
		replicas: 1
		image: {
			registry: "redis"
			tag: "8.8-alpine"
			pullPolicy: "Always"
		}
		resources: {
			requests: {
				cpu: "100m"
				memory: "128Mi"
			}
			limits: {
				cpu: "500m"
				memory: "512Mi"
			}
		}
		pdb: {
			enabled: true
		}
		auth: {
			password: "ChangeMe123!"
		}
		master: {
			extraFlags: [
				"--maxmemory-policy volatile-lru",
				"--maxmemory 768mb",
			]
		}
		replica: {
			replicaCount: 1
			extraFlags: [
				"--maxmemory-policy volatile-lru",
				"--maxmemory 768mb",
			]
		}
	}
	opensearch: {
		image: "opensearchproject/opensearch:2.19.6"
		initialAdminPassword: "ChangeMe123!"
		disableSecurityPlugin: true
	}
	rabbitmq: {
		image: "rabbitmq:4-management"
		username: "guest"
		password: "guest"
	}

	supervisord: {
		enabled: true
		replicas: 1
		image: {
			registry: "pimcore/pimcore"
			tag: "php8.5-supervisord-5.x"
			pullPolicy: "IfNotPresent"
		}
		resources: {
			requests: {
				cpu: "100m"
				memory: "256Mi"
				"ephemeral-storage": "256Mi"
			}
			limits: {
				cpu: "500m"
				memory: "512Mi"
				"ephemeral-storage": "512Mi"
			}
		}
	}

	mercure: {
		enabled: true
		replicas: 1
		image: {
			registry: "dunglas/mercure"
			tag: "latest"
			pullPolicy: "IfNotPresent"
		}
		publisherJwtKey: "!ChangeThisMercureHubJWTSecretKey!"
		subscriberJwtKey: "!ChangeThisMercureHubJWTSecretKey!"
		extraDirectives: "anonymous"
		resources: {
			requests: {
				cpu: "50m"
				memory: "64Mi"
				"ephemeral-storage": "128Mi"
			}
			limits: {
				cpu: "200m"
				memory: "128Mi"
				"ephemeral-storage": "256Mi"
			}
		}
	}

	s3: {
		enabled: false
		key: ""
		secret: ""
		publicBucket: ""
		privateBucket: ""
	}

	serviceAccount: {
		create: true
		annotations: {}
		name: ""
	}

	podSecurityContext: {
		fsGroup: 33
		seccompProfile: {
			type: "RuntimeDefault"
		}
	}
	securityContext: {
		allowPrivilegeEscalation: false
		capabilities: {
			drop: [
				"ALL",
			]
			add: [
				"NET_BIND_SERVICE",
				"SETGID",
				"SETUID",
			]
		}
	}

	autoscaling: {
		enabled: false
		minReplicas: 1
		maxReplicas: 100
		targetCPUUtilizationPercentage: 80
	}

	nodeSelector: {}
	tolerations: {}
	affinity: {}
}
