{{- if not .Values.secrets.app.useExisting }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hievents.appSecretName" . }}
  labels:
    {{- include "hievents.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.app.appKeySecretKey }}: {{ required "secrets.appKeySecretKey  is required unless secrets.app.useExisting=true" .Values.secrets.app.appKey | quote }}
  {{ .Values.secrets.app.jwtSecretKey }}: {{ required "secrets.app.jwtSecret is required unless secrets.app.useExisting=true" .Values.secrets.app.jwtSecret | quote }}
  {{ .Values.secrets.app.stripePublishableKeyKey }}: {{ .Values.secrets.app.stripePublishableKey | quote }}
  {{ .Values.secrets.app.stripeSecretKeyKey }}: {{ .Values.secrets.app.stripeSecretKey | quote }}
  {{ .Values.secrets.app.stripeWebhookSecretKey }}: {{ .Values.secrets.app.stripeWebhookSecret | quote }}
{{- end }}
---
{{- if not .Values.secrets.postgresql.useExisting }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hievents.postgresqlSecretName" . }}
  labels:
    {{- include "hievents.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.postgresql.passwordKey }}: {{ required "secrets.postgresql.password is required unless secrets.postgresql.useExisting=true" .Values.secrets.postgresql.password | quote }}
{{- end }}
---
{{- if not .Values.secrets.redis.useExisting }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hievents.redisSecretName" . }}
  labels:
    {{- include "hievents.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.redis.passwordKey }}: {{ required "secrets.redis.password is required unless secrets.redis.useExisting=true" .Values.secrets.redis.password | quote }}
{{- end }}
---
{{- if and .Values.secrets.mail.password (not .Values.secrets.mail.useExisting) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hievents.mailSecretName" . }}
  labels:
    {{- include "hievents.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.mail.passwordKey }}: {{ .Values.secrets.mail.password | quote }}
{{- end }}
---
{{- if and (eq .Values.hieventsConfig.storage.driver "s3") (not .Values.secrets.s3.useExisting) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hievents.s3SecretName" . }}
  labels:
    {{- include "hievents.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.s3.accessKeyIdKey }}: {{ required "secrets.s3.accessKeyId is required unless secrets.s3.useExisting=true" .Values.secrets.s3.accessKeyId | quote }}
  {{ .Values.secrets.s3.secretAccessKeyKey }}: {{ required "secrets.s3.secretAccessKey is required unless secrets.s3.useExisting=true" .Values.secrets.s3.secretAccessKey | quote }}
{{- end }}
