// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.
// Reference: https://github.com/christianhuth/helm-charts/blob/main/charts/shlink-backend/values.yaml

@if(!debug)

package main

values: {
	nameOverride:     ""
	fullnameOverride: ""
	global: {
		security: {
			allowInsecureImages: true
		}
	}
	image: {
		registry:   "docker.io"
		repository: "shlinkio/shlink"
		pullPolicy: "Always"
		tag:        "5.1.5"
	}
	imagePullSecrets: []
	replicaCount: 1
	revisionHistoryLimit: 10

	serviceAccount: {
		create: true
		annotations: {}
		name: ""
	}

	podAnnotations: {}
	podLabels: {}
	podSecurityContext: {
		runAsNonRoot: true
		runAsUser:    10001
		runAsGroup:   10001
		seccompProfile: {
			type: "RuntimeDefault"
		}
	}
	securityContext: {
		runAsNonRoot: true
		runAsUser:    10001
		runAsGroup:   10001
		readOnlyRootFilesystem: true
		capabilities: {
			drop: ["ALL"]
		}
	}

	service: {
		type: "ClusterIP"
		port: 8080
	}

	ingress: {
		enabled: false
		className: ""
		annotations: {}
		hosts: [{
			host: "chart-example.local"
			paths: [{
				path: "/"
				pathType: "ImplementationSpecific"
			}]
		}]
		tls: []
	}

	route: main: {
		enabled: true
		apiVersion: "gateway.networking.k8s.io/v1"
		kind: "HTTPRoute"
		annotations: {}
		labels: {}
		hostnames: []
		parentRefs: []
		matches: [{
			path: {
				type: "PathPrefix"
				value: "/"
			}
		}]
		filters: []
		additionalRules: []
		httpsRedirect: false
		timeouts: {}
	}

	resources: {
		limits: {
			cpu: "2"
			memory: "2Gi"
		}
		requests: {
			cpu: "100m"
			memory: "128Mi"
		}
	}
	autoscaling: {
		enabled: true
		minReplicas: 1
		maxReplicas: 3
		targetCPUUtilizationPercentage: 80
	}
	deploymentStrategy: {}
	nodeSelector: {}
	tolerations: []
	affinity: {}
	extraEnv: []

	config: {
		database: {
			auth: {
				database: ""
				existingSecret: ""
				password: ""
				username: ""
			}
			driver: "sqlite"
			host: ""
			port: 0
			useEncryption: false
		}
		general: {
			basePath: ""
			cacheNamespace: ""
			defaultDomain: "localhost:8080"
			initialApiKey: "my-super-secret-api-key"
			isHttpsEnabled: false
			memoryLimit: ""
			timezone: ""
		}
		geolite: {
			licenseKey: ""
			skipInitialDownload: false
		}
		matomo: {
			enabled: false
			auth: {
				apiToken: ""
				existingSecret: ""
			}
			baseUrl: ""
			siteId: ""
		}
		mercure: {
			enabled: false
			auth: {
				jwtSecret: ""
				existingSecret: ""
			}
			publicHubUrl: ""
			internalHubUrl: ""
		}
		qrCodes: {
			codeForDisabledShortUrls: true
			defaultColors: {
				background: "#FFFFFF"
				foreground: "#000000"
			}
			defaultErrorCorrection: "l"
			defaultFormat: "png"
			defaultLogoUrl: ""
			defaultMargin: 0
			defaultRoundBlockSize: true
			defaultSize: 300
		}
		rabbitmq: {
			enabled: false
			auth: {
				existingSecret: ""
				password: ""
				username: ""
			}
			host: ""
			port: 0
			useSsl: false
			vhost: "/"
		}
		redirects: {
			cacheLifetime: 30
			defaultBaseUrlRedirect: ""
			defaultInvalidShortUrlRedirect: ""
			defaultRegular404Redirect: ""
			extraPathMode: "default"
			statusCode: 302
		}
		redis: {
			enabled: false
			pubSubEnabled: false
			sentinal: {
				enabled: true
				service: ""
			}
			servers: ""
		}
		robots: {
			allowAllShortUrls: false
			userAgents: "*"
		}
		trackingVisits: {
			anonymizeRemoteAddr: true
			disable: false
			disableIpTracking: false
			disableReferrerTracking: false
			disableTrackingParam: ""
			disableTrackingFrom: ""
			disableUaTracking: false
			trackOrphanVisits: true
		}
		urlShortening: {
			autoResolveTitles: true
			defaultShortCodesLength: 5
			deleteShortUrlThreshold: ""
			multiSegmentSlugsEnabled: false
			shortUrlMode: "strict"
			shortUrlTrailingSlash: false
		}
	}

	mariadb: {
		enabled: false
		auth: {
			database: "shlink"
			password: "shlink"
			username: "shlink"
		}
		image: {
			repository: "bitnamilegacy/mariadb"
			tag:        "12.0.2-debian-12-r0"
		}
	}
	mysql: {
		enabled: false
		auth: {
			database: "shlink"
			password: "shlink"
			username: "shlink"
		}
		image: {
			repository: "bitnamilegacy/mysql"
			tag:        "9.4.0-debian-12-r1"
		}
	}
	postgresql: {
		enabled: true
		auth: {
			database: "shlink"
			password: "shlink"
			username: "shlink"
		}
		image: {
			repository: "bitnamilegacy/postgresql"
			tag:        "17.6.0-debian-12-r4"
		}
	}
	rabbitmq: {
		enabled: false
		image: {
			repository: "bitnamilegacy/rabbitmq"
			tag:        "4.1.3-debian-12-r1"
		}
	}
	redis: {
		enabled: true
		architecture: "standalone"
		auth: {
			enabled: false
			sentinel: true
		}
		sentinel: {
			enabled: false
		}
		image: {
			repository: "bitnamilegacy/redis"
			tag:        "8.2.1-debian-12-r0"
		}
	}
	// Below parameters are for the web components
	// Reference: https://github.com/christianhuth/helm-charts/blob/main/charts/shlink-web/values.yaml
	web: {
		enabled: true
		image: {
			registry:   "docker.io"
			repository: "shlinkio/shlink-web-client"
			pullPolicy: "Always"
			tag:        "4.8.0"
		}
		imagePullSecrets: []
		replicaCount: 1
		revisionHistoryLimit: 10
		serviceAccount: {
			create:      true
			annotations: {}
			name:        ""
		}
		podAnnotations: {}
		podLabels: {}
		podSecurityContext: {
			runAsNonRoot: true
			runAsUser:    10001
			runAsGroup:   10001
			seccompProfile: {
				type: "RuntimeDefault"
			}
		}
		securityContext: {
			runAsNonRoot: true
			runAsUser:    10001
			runAsGroup:   10001
			readOnlyRootFilesystem: true
			capabilities: {
				drop: ["ALL"]
			}
		}
		service: {
			type: "ClusterIP"
			port: 80
		}
		ingress: {
			enabled: false
			className: ""
			annotations: {}
			hosts: [
				{
					host: "chart-example.local"
					paths: [
						{
							path: "/"
							pathType: "ImplementationSpecific"
						}
					]
				}
			]
			tls: []
		}
		route: main: {
			enabled: true
			apiVersion: "gateway.networking.k8s.io/v1"
			kind: "HTTPRoute"
			annotations: {}
			labels: {}
			hostnames: []
			parentRefs: []
			matches: [
				{
					path: {
						type: "PathPrefix"
						value: "/"
					}
				}
			]
			filters: []
			additionalRules: []
			httpsRedirect: false
			timeouts: {}
		}
		resources: {
			limits: {
				cpu: "100m"
				memory: "128Mi"
			}
			requests: {
				cpu: "50m"
				memory: "64Mi"
			}
		}
		autoscaling: {
			enabled: true
			minReplicas: 1
			maxReplicas: 2
			targetCPUUtilizationPercentage: 80
		}
		deploymentStrategy: {}
		nodeSelector: {}
		tolerations: []
		affinity: {}
		configuration: [
			{
				name:   "Local Shlink Backend"
				url:    "http://localhost:8080"
				apiKey: "my-super-secret-api-key"
			},
		]
		extraEnv: []
	}
}