// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.
// Reference: https://github.com/christianhuth/helm-charts/blob/main/charts/countly/values.yaml

@if(!debug)

package main

// Defaults
values: {
	// -- Provide a name in place of `baserow`
	nameOverride:     ""
	// -- String to fully override `"baserow.fullname"`
	fullnameOverride: ""

	api: {
		image: {
			// -- image registry
			registry:   "docker.io"
			// -- image repository
			repository: "countly/api"
			// -- Overrides the image tag
			tag:        "25.05.4"
			// -- image pull policy
			pullPolicy: "Always"
		}
		// -- If defined, uses a Secret to pull an image from a private Docker registry or repository.
		imagePullSecrets: []
		// -- Annotations to be added to the frontend pods
		podAnnotations: {}
		// -- pod-level security context
		podSecurityContext: {
			runAsUser:    65510
			runAsGroup:   65510
			fsGroup:      65510
		}
		// -- Pod priority class name
		priorityClassName:    ""
		// -- Number of replicas
		replicaCount:         1
		// -- The number of old ReplicaSets to retain
		revisionHistoryLimit: 10
		// -- Resource limits and requests for the controller pods.
		// @default -- see [values.yaml](./values.yaml)
		resources: {
			limits: {
				cpu:    "1000m"
				memory: "2Gi"
			}
			requests: {
				cpu:    "200m"
				memory: "400Mi"
			}
		}
		// container-level security context
		securityContext: {
			runAsNonRoot:           true
			readOnlyRootFilesystem: true
			capabilities: drop: ["ALL"]
		}
		serviceAccount: {
			// -- Specifies whether a service account should be created
			create:      true
			// -- Annotations to add to the service account
			annotations: {}
			// -- The name of the service account to use.
			// If not set and create is true, a name is generated using the fullname template
			name:        ""
		}
		service: {
			// -- Kubernetes service type
			type: "ClusterIP"
			// -- Kubernetes port where service is exposed
			port: 3000
		}
		// BETA: Configure the gateway routes for the chart here.
		// More routes can be added by adding a dictionary key like the 'main' route.
		// Being BETA this can/will change in the future without notice, do not use unless you want to take that risk
		// [[ref]](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1alpha2)
		route: {
			main: {
				// -- Enables or disables the route
				enabled:        true
				// -- Set the route apiVersion, e.g. gateway.networking.k8s.io/v1 or gateway.networking.k8s.io/v1alpha2
				apiVersion:     "gateway.networking.k8s.io/v1"
				// -- Set the route kind
				// Valid options are GRPCRoute, HTTPRoute, TCPRoute, TLSRoute, UDPRoute
				kind:           "HTTPRoute"
				// -- Add annotations to the route
				annotations:   {}
				// -- Add labels to the route
				labels:        {}
				// -- Hostnames to be matched
				// - my-filter.example.com
				hostnames:    ["localhost"] // fqdn of the service
				// -- Parent references (Gateway)
				// - name: acme-gw
				parentRefs: [{
					name:      "shared-gtw"
					namespace: "kube-system"
				}]
				// -- define conditions used for matching the rule against incoming HTTP requests.
				// @default -- see [values.yaml](./values.yaml)
				matches: [
					{
						path: {
							type:  "PathPrefix"
							value: "/i"
						}
					},
					{
						path: {
							type:  "PathPrefix"
							value: "/i/*"
						}
					},
					{
						path: {
							type:  "PathPrefix"
							value: "/o"
						}
					},
					{
						path: {
							type:  "PathPrefix"
							value: "/o/*"
						}
					},
				]
				// -- Filters define the filters that are applied to requests that match this rule.
				filters:         []
				// -- Additional custom rules that can be added to the route
				additionalRules: []
				// -- adds a filter for redirecting to https (HTTP 301 Moved Permanently). To redirect HTTP traffic to HTTPS, you need to have a Gateway with both HTTP and HTTPS listeners. Matches and filters do not take effect if enabled. Ref. https://gateway-api.sigs.k8s.io/guides/http-redirect-rewrite/
				httpsRedirect:   false
				// -- defines the timeouts that can be configured for an HTTP request
				timeouts:        {}
			}
		}
		autoscaling: {
			// -- Enable Horizontal POD autoscaling
			enabled:                           false
			// -- Minimum number of replicas
			minReplicas:                       1
			// -- Maximum number of replicas
			maxReplicas:                       100
			// -- Target CPU utilization percentage
			targetCPUUtilizationPercentage:    80
			// -- Target Memory utilization percentage
			targetMemoryUtilizationPercentage: 80
		}
		livenessProbe: {
			// -- Failure threshold for livenessProbe
			failureThreshold:    6
			// -- Initial delay seconds for livenessProbe
			initialDelaySeconds: 60
			// -- Period seconds for livenessProbe
			periodSeconds:       30
			// -- Success threshold for livenessProbe
			successThreshold:    1
			// -- Timeout in seconds for livenessProbe
			timeoutSeconds:      2
		}
		readinessProbe: {
			// -- Failure threshold for readinessProbe
			failureThreshold:    6
			// -- Initial delay seconds for readinessProbe
			initialDelaySeconds: 60
			// -- Period seconds for readinessProbe
			periodSeconds:       30
			// -- Success threshold for readinessProbe
			successThreshold:    1
			// -- Timeout in seconds for readinessProbe
			timeoutSeconds:      2
		}
		// -- Node labels for pod assignment
		nodeSelector: {}
		// -- Toleration labels for pod assignment
		tolerations:  []
		// -- Affinity settings for pod assignment
		affinity:     {}
		// -- Additional labels to add to the pod
		selectorLabels: {}
		// -- additional environment variables to be added to the api pods
		extraEnv:     []
	}

	frontend: {
		image: {
			// -- image registry
			registry:   "docker.io"
			// -- image repository
			repository: "countly/frontend"
			// -- Overrides the image tag
			tag:        "25.05.4"
			// -- image pull policy
			pullPolicy: "Always"
		}
		// -- If defined, uses a Secret to pull an image from a private Docker registry or repository.
		imagePullSecrets: []
		// -- Annotations to be added to the frontend pods
		podAnnotations: {}
		// -- pod-level security context
		podSecurityContext: {
			runAsUser:    65510
			runAsGroup:   65510
			fsGroup:      65510
		}
		// -- Pod priority class name
		priorityClassName:    ""
		// -- Number of replicas
		replicaCount:         1
		// -- The number of old ReplicaSets to retain
		revisionHistoryLimit: 10
		// -- Resource limits and requests for the controller pods.
		// @default -- see [values.yaml](./values.yaml)
		resources: {
			limits: {
				cpu:    "500m"
				memory: "500Mi"
			}
			requests: {
				cpu:    "100m"
				memory: "100Mi"
			}
		}
		// -- container-level security context
		securityContext: {
			runAsNonRoot:           true
			readOnlyRootFilesystem: false
			capabilities: drop: ["ALL"]
		}
		serviceAccount: {
			// -- Specifies whether a service account should be created
			create:      true
			// -- Annotations to add to the service account
			annotations: {}
			// -- The name of the service account to use.
			// If not set and create is true, a name is generated using the fullname template
			name:        ""
		}
		service: {
			// -- Kubernetes service type
			type: "ClusterIP"
			// -- Kubernetes port where service is exposed
			port: 3000
		}
		// BETA: Configure the gateway routes for the chart here.
		// More routes can be added by adding a dictionary key like the 'main' route.
		// Being BETA this can/will change in the future without notice, do not use unless you want to take that risk
		// [[ref]](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1alpha2)
		route: {
			main: {
				// -- Enables or disables the route
				enabled:        true
				// -- Set the route apiVersion, e.g. gateway.networking.k8s.io/v1 or gateway.networking.k8s.io/v1alpha2
				apiVersion:     "gateway.networking.k8s.io/v1"
				// -- Set the route kind
				// Valid options are GRPCRoute, HTTPRoute, TCPRoute, TLSRoute, UDPRoute
				kind:           "HTTPRoute"
				// -- Add annotations to the route
				annotations:   {}
				// -- Add labels to the route
				labels:        {}
				// -- Hostnames to be matched
				// - my-filter.example.com
				hostnames:      ["localhost"]
				// -- Parent references (Gateway)
				// - name: acme-gw
				parentRefs: [{
					name:      "shared-gtw"
					namespace: "kube-system"
				}]
				// -- define conditions used for matching the rule against incoming HTTP requests.
				// @default -- see [values.yaml](./values.yaml)
				matches: [
					{
						path: {
							type:  "PathPrefix"
							value: "/"
						}
					},
					{
						path: {
							type:  "PathPrefix"
							value: "/images/"
						}
					},
				]
				// Filters define the filters that are applied to requests that match this rule.
				filters:         []
				// Additional custom rules that can be added to the route
				additionalRules: []
				// adds a filter for redirecting to https
				httpsRedirect:   false
				// defines the timeouts that can be configured for an HTTP request
				timeouts:        {}
			}
		}
		autoscaling: {
			// Enable Horizontal POD autoscaling
			enabled:                           false
			// Minimum number of replicas
			minReplicas:                       1
			// Maximum number of replicas
			maxReplicas:                       100
			// Target CPU utilization percentage
			targetCPUUtilizationPercentage:    80
			// Target Memory utilization percentage
			targetMemoryUtilizationPercentage: 80
		}
		livenessProbe: {
			// Failure threshold for livenessProbe
			failureThreshold:    6
			// Initial delay seconds for livenessProbe
			initialDelaySeconds: 60
			// Period seconds for livenessProbe
			periodSeconds:       30
			// Success threshold for livenessProbe
			successThreshold:    1
			// Timeout in seconds for livenessProbe
			timeoutSeconds:      2
		}
		readinessProbe: {
			// Failure threshold for readinessProbe
			failureThreshold:    6
			// Initial delay seconds for readinessProbe
			initialDelaySeconds: 60
			// Period seconds for readinessProbe
			periodSeconds:       30
			// Success threshold for readinessProbe
			successThreshold:    1
			// Timeout in seconds for readinessProbe
			timeoutSeconds:      2
		}
		// Node labels for pod assignment
		nodeSelector: {}
		// Toleration labels for pod assignment
		tolerations:  []
		// Affinity settings for pod assignment
		affinity:     {}
		// Additional labels to add to the pod
		selectorLabels: {}
		// additional environment variables to be added to the frontend pods
		extraEnv:     []
	}

	// additional environment variables to be added to both api and frontend pods
	extraEnv: []

	// General configuration shared between the frontend and api
	config: {
		api: {
			filestorage: "gridfs"
			mail: {
				// Enable sending of emails
				enabled: false
				auth: {
					// Use existing secret for password details. The secret has to contain the key `mail-password`.
					existingSecret: ""
					// The password to authenticate to the smtp host when sending emails.
					password:       ""
					// The username to authenticate to the smtp host when sending emails.
					username:       ""
				}
				// The email address Countly will send emails from.
				from: ""
				// The host of the external SMTP server that Countly should use to send emails.
				host: ""
				// The port used to connect to the smtp host.
				port: 0
			}
			workerCount: "1"
		}
		nodeOptions: "--max-old-space-size=2048"
		// List of plugins : https://community.count.ly/plugins
		plugins:     "mobile,web,desktop,plugins,density,locale,browser,sources,views,logger,systemlogs,populator,reports,crashes,push,star-rating,slipping-away-users,compare,server-stats,dbviewer,times-of-day,compliance-hub,alerts,onboarding,consolidate,remote-config,hooks,dashboards,sdk,data-manager,guides"
	}

	mongodb: {
		// enable MongoDB
		enabled:        true
		// MongoDB architecture. Currently only standalone is supported by this Chart.
		architecture:   "standalone"
		// WARNING: MongoDB versions are strictly incompatible with Linux kernel 
		// versions 6.19 through 7.0.13 due to an upstream TCMalloc bug clashing 
		// with CET Shadow Stack, resulting in an immediate startup crash loop.
		// SOLUTION: To fix this permanently on modern host systems without runtime hacks, 
		// we downgraded the image tag to MongoDB 7.0. Alternatively, the host Linux 
		// kernel can be upgraded to version 7.0.14 or later to resolve the bug natively.
		// OFFICIAL REFERENCE: https://www.mongodb.com/docs/manual/administration/production-notes/
		image: {
			registry:   "docker.io"
			repository: "library/mongo"
			tag:        "7.0"
			pullPolicy: "IfNotPresent"
		}
		auth: {
			// Enable authentication
			enabled:  false
			// Name for a custom database to create
			database: "countly"
			password: "countly"
			username: "countly"
		}

		podSecurityContext: {
			runAsUser:           65510
			runAsGroup:          65510
			fsGroup:             65510
		}
		securityContext: {
			capabilities: {
				drop: [
					"ALL",
				]
			}
		}
	
		resources: {
			limits: {
				cpu:    "500m"
				memory: "1Gi"
			}
			requests: {
				cpu:    "100m"
				memory: "256Mi"
			}
		}
		// Set to true to use a StatefulSet instead of a Deployment
		useStatefulSet: true
	}

	externalMongodb: {
		auth: {
			// Name for a custom database to use
			database: "countly"
		}
		// Hostname of the MongoDB database
		hostname: ""
		// Port used to connect to MongoDB database
		port:     27017
	}
}
