// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.
// Reference: https://github.com/helmforgedev/charts/blob/main/charts/heimdall/values.yaml

@if(!debug)

package main

// Defaults
values: {
	// =============================================================================
	// Metadata & Overrides
	// =============================================================================

	// -- Override the chart name
	nameOverride: ""

	// -- Override the full release name
	fullnameOverride: ""

	// -- Labels to add to all resources
	commonLabels: {}

	// =============================================================================
	// Image
	// =============================================================================

	image: {
		// -- Container image repository
		repository: "docker.io/linuxserver/heimdall"
		// -- Image tag
		tag: "2.8.3"
		// -- Image pull policy
		pullPolicy: "IfNotPresent"
		// -- Image digest
		digest: ""
	}

	// -- Image pull secrets for private registries
	imagePullSecrets: []

	// =============================================================================
	// Heimdall Configuration
	// =============================================================================

	heimdall: {
		// -- User ID for file permissions
		puid: 1000
		// -- Group ID for file permissions
		pgid: 1000
		// -- Timezone (e.g., "America/New_York", "Europe/London")
		timezone: "UTC"
		// -- Extra environment variables
		extraEnv: []
	}

	// =============================================================================
	// Persistence
	// =============================================================================

	persistence: {
		// -- Enable persistent storage for /config
		enabled: true
		// -- Storage class (empty for cluster default)
		storageClass: ""
		// -- Access mode
		accessMode: "ReadWriteOnce"
		// -- Volume size
		size: "1Gi"
		// -- Use an existing PVC
		existingClaim: ""
		// -- PVC annotations
		annotations: {}
	}

	// =============================================================================
	// S3 Backup
	// =============================================================================

	backup: {
		// -- Enable S3 backup CronJob
		enabled: false
		// -- Cron schedule (default: daily at 03:00 UTC)
		schedule: "0 3 * * *"
		// -- Suspend the CronJob
		suspend: false
		// -- Concurrency policy
		concurrencyPolicy: "Forbid"
		// -- Successful job history limit
		successfulJobsHistoryLimit: 3
		// -- Failed job history limit
		failedJobsHistoryLimit: 3
		// -- Backoff limit
		backoffLimit: 1
		// -- Archive filename prefix
		archivePrefix: "heimdall"

		images: {
			// -- Image for creating tar archives
			archiver: "docker.io/library/alpine:3.22"
			// -- Image for uploading to S3
			uploader: "docker.io/helmforge/mc:1.0.0"
		}

		// -- Resource requests and limits for backup jobs
		resources: {}

		s3: {
			// -- S3-compatible endpoint URL
			endpoint: ""
			// -- S3 bucket name
			bucket: ""
			// -- S3 key prefix
			prefix: "heimdall"
			// -- Create bucket if it does not exist
			createBucketIfNotExists: true
			// -- Existing secret with S3 credentials
			existingSecret: ""
			// -- Key in existing secret for access key
			existingSecretAccessKeyKey: "access-key"
			// -- Key in existing secret for secret key
			existingSecretSecretKeyKey: "secret-key"
			// -- S3 access key (use existingSecret in production)
			accessKey: ""
			// -- S3 secret key (use existingSecret in production)
			secretKey: ""
		}
	}

	// =============================================================================
	// Pod Configuration
	// =============================================================================

	resources: {
		requests: {
			cpu:    "50m"
			memory: "128Mi"
		}
		limits: {
			memory: "256Mi"
			cpu: "500m"
		}
	}

	podSecurityContext: {}

	securityContext: {}

	startupProbe: {
		// -- Enable startup probe
		enabled:             true
		path:                "/"
		initialDelaySeconds: 5
		periodSeconds:       5
		timeoutSeconds:      3
		failureThreshold:    12
	}

	livenessProbe: {
		// -- Enable liveness probe
		enabled:             true
		path:                "/"
		initialDelaySeconds: 0
		periodSeconds:       20
		timeoutSeconds:      5
		failureThreshold:    3
	}

	readinessProbe: {
		// -- Enable readiness probe
		enabled:             true
		path:                "/"
		initialDelaySeconds: 0
		periodSeconds:       10
		timeoutSeconds:      5
		failureThreshold:    3
	}

	// =============================================================================
	// Service
	// =============================================================================

	service: {
		// -- Service type
		type: "ClusterIP"
		// -- Service port
		port: 80
		// -- Annotations for the service
		annotations: {}
	}

	// =============================================================================
	// Ingress
	// =============================================================================

	ingress: {
		// -- Enable ingress
		enabled:          false
		ingressClassName: ""
		annotations: {}
		hosts: []
		tls: []
	}

	// =============================================================================
	// Service Account
	// =============================================================================

	serviceAccount: {
		// -- Create a service account
		create: true
		// -- Automatically mount a ServiceAccount's API credentials
		automountServiceAccountToken: false
		// -- Service account name
		name: ""
		// -- Annotations for the service account
		annotations: {}
	}

	// =============================================================================
	// Scheduling
	// =============================================================================

	nodeSelector: {}
	tolerations: []
	affinity: {}
	topologySpreadConstraints: []
	priorityClassName:             ""
	terminationGracePeriodSeconds: 30

	// =============================================================================
	// Extra
	// =============================================================================

	podLabels: {}
	podAnnotations: {}
	extraVolumeMounts: []
	extraVolumes: []
	extraManifests: []
}
