// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.
// Reference: https://github.com/helmforgedev/charts/blob/main/charts/openhab/values.yaml

@if(!debug)

package main

// Defaults
values: {
	// =============================================================================
	// Container Image
	// =============================================================================

	// -- Container image configuration
	image: {
		// -- Image repository
		repository: "docker.io/openhab/openhab"
		// -- Image pull policy
		pullPolicy: "IfNotPresent"
		// -- Image tag (defaults to chart appVersion). Never use 'latest'.
		tag: "5.2.1"
	}

	// -- Image pull secrets
	imagePullSecrets: []

	// -- Number of replicas.
	// @default -- 1
	// WARNING: openHAB does NOT support horizontal scaling. This MUST remain 1.
	replicaCount: 1

	// -- Override the chart name
	nameOverride: ""

	// -- Override the full release name
	fullnameOverride: ""

	// -- Override the namespace used by chart-managed namespaced resources. The target namespace must already exist.
	namespaceOverride: ""

	// -- ServiceAccount configuration
	serviceAccount: {
		// -- Create a ServiceAccount
		create: true
		// -- Mount the Kubernetes API token into the pod
		automountServiceAccountToken: false
		// -- Annotations to add to the ServiceAccount
		annotations: {}
		// -- Name of the ServiceAccount (defaults to release name)
		name: ""
	}

	// -- Annotations to add to the pod
	podAnnotations: {}

	// -- Labels to add to the pod
	podLabels: {}

	// -- Pod-level security context.
	// fsGroup: 9001 ensures mounted PVC directories are group-accessible after the
	// entrypoint drops privileges to UID 9001 via gosu.
	//
	// runAsUser and runAsGroup are intentionally NOT set here.
	// The openHAB image entrypoint starts as root, creates the 'openhab' user/group
	// (UID/GID 9001) if absent, chowns the data directories, then execs
	// 'gosu openhab' to drop privileges. Setting runAsUser: 9001 would break
	// this initialization sequence (groupadd/useradd require root).
	podSecurityContext: {
		fsGroup: 9001
		seccompProfile: {
			type: "RuntimeDefault"
		}
	}

	// -- Container-level security context.
	// capabilities restrictions are intentionally omitted: the entrypoint requires
	// CAP_SETUID, CAP_SETGID, and CAP_CHOWN during initialization before dropping
	// to the openhab user.
	// readOnlyRootFilesystem must remain false - openHAB writes to internal dirs at runtime.
	securityContext: {
		allowPrivilegeEscalation: false
		readOnlyRootFilesystem:   false
	}

	// -- Service configuration
	service: {
		// -- Service type
		type: "ClusterIP"
		// -- HTTP port
		port: 8080
		// -- Set the ipFamilyPolicy for dual-stack (GR-058)
		ipFamilyPolicy: ""
		// -- Set the ipFamilies for dual-stack
		ipFamilies: []
	}

	// =============================================================================
	// Storage Persistence
	// =============================================================================

	// -- Persistent storage for openHAB data directories
	persistence: {
		// -- userdata: Runtime state, JSONDB, logs, persistence data (REQUIRED)
		userdata: {
			// -- Enable PVC for userdata
			enabled: true
			// -- Storage class name (empty = cluster default)
			storageClass: ""
			// -- Access mode
			accessMode: "ReadWriteOnce"
			// -- Storage size
			size: "5Gi"
			// -- Use an existing PVC instead of creating one
			existingClaim: ""
		}

		// -- conf: Configuration files synced before startup (REQUIRED)
		conf: {
			// -- Enable PVC for conf
			enabled: true
			// -- Storage class name (empty = cluster default)
			storageClass: ""
			// -- Access mode
			accessMode: "ReadWriteOnce"
			// -- Storage size
			size: "1Gi"
			// -- Use an existing PVC instead of creating one
			existingClaim: ""
		}

		// -- addons: Drop-in JAR addons not available via marketplace (optional)
		addons: {
			// -- Enable PVC for addons
			enabled: true
			// -- Storage class name (empty = cluster default)
			storageClass: ""
			// -- Access mode
			accessMode: "ReadWriteOnce"
			// -- Storage size
			size: "2Gi"
			// -- Use an existing PVC instead of creating one
			existingClaim: ""
		}
	}

	// =============================================================================
	// Admin Credentials Reference
	// =============================================================================

	// -- Admin credentials configuration.
	// openHAB does not support env-var-based admin bootstrap natively.
	// On first boot, create the admin user through the web UI at port 8080.
	admin: {
		// -- Create a Secret to store admin credentials as a reference
		secretEnabled: false
		// -- Admin username (stored in Secret for reference only)
		username: "admin"
		// -- Admin password (stored in Secret for reference only - NOT injected automatically)
		password: ""
		// -- Use an existing Secret (must contain keys: username, password)
		existingSecret: ""
	}

	// =============================================================================
	// Provisioning ConfigMaps
	// =============================================================================

	// -- ConfigMap-based configuration files copied into the conf PVC before startup.
	// Helm upgrades roll the pod through a checksum annotation when these values change.
	configMaps: {
		// -- Image used by the init container that copies ConfigMap files into the conf PVC
		syncImage: {
			repository: "docker.io/library/busybox"
			tag:        "1.37"
			pullPolicy: "IfNotPresent"
		}
		// -- Resource requests/limits for the ConfigMap sync init container
		syncResources: {
			requests: {
				cpu:    "10m"
				memory: "16Mi"
			}
			limits: {
				cpu:    "100m"
				memory: "64Mi"
			}
		}
		// -- Sitemap files mounted to /openhab/conf/sitemaps/
		sitemaps: {
			// -- Enable sitemap ConfigMap
			enabled: true
			// -- Map of filename -> file content
			files: {}
		}
		// -- Things files mounted to /openhab/conf/things/
		things: {
			// -- Enable things ConfigMap
			enabled: true
			// -- Map of filename -> file content
			files: {}
		}
		// -- Items files mounted to /openhab/conf/items/
		items: {
			// -- Enable items ConfigMap
			enabled: true
			// -- Map of filename -> file content
			files: {}
		}
	}

	// =============================================================================
	// Environment Variables
	// =============================================================================

	// -- Environment variables for the openHAB container
	env: {
		// -- Timezone (e.g. Europe/Berlin, America/Sao_Paulo)
		TZ: "UTC"
		// -- Extra JVM options (e.g. -Xms512m -Xmx1g)
		EXTRA_JAVA_OPTS: ""
		// -- HTTP port (must match service.port)
		OPENHAB_HTTP_PORT: "8080"
		// -- HTTPS port
		OPENHAB_HTTPS_PORT: "8443"
	}

	// =============================================================================
	// Apache Karaf SSH Console
	// =============================================================================

	// -- Apache Karaf SSH admin console (port 8101)
	karaf: {
		// -- Enable Karaf SSH service
		enabled: true
		service: {
			// -- Service type for Karaf SSH
			type: "ClusterIP"
			// -- Karaf SSH port
			port: 8101
			// -- Set the ipFamilyPolicy for Karaf SSH Service (dual-stack)
			ipFamilyPolicy: ""
			// -- Set the ipFamilies for Karaf SSH Service
			ipFamilies: []
		}
	}

	// =============================================================================
	// Resource Requests & Limits
	// =============================================================================

	// -- Resource requests and limits
	resources: {
		requests: {
			cpu:    "500m"
			memory: "512Mi"
		}
		limits: {
			cpu:    "2000m"
			memory: "2Gi"
		}
	}

	// =============================================================================
	// Probes
	// =============================================================================

	// -- Startup probe - allows openHAB time to load all OSGi bundles.
	// Uses /rest/uuid which returns 200 (no auth) as soon as the REST API is ready.
	// NOTE: /rest/alive does NOT exist in openHAB 4.x - use /rest/uuid instead.
	// On first boot this can take 2-5 minutes; on slow hardware up to 10 minutes.
	// The probe window = failureThreshold - periodSeconds.
	startupProbe: {
		httpGet: {
			path: "/rest/uuid"
			port: "http"
		}
		// Avoid noisy first-boot probe warning events while OSGi starts.
		initialDelaySeconds: 60
		// 60 attempts x 10s = 10 minutes maximum startup window.
		// Keep this generous: openHAB's OSGi bundle loading depends heavily on hardware.
		failureThreshold: 60
		periodSeconds:       10
	}

	// -- Liveness probe
	livenessProbe: {
		httpGet: {
			path: "/rest/uuid"
			port: "http"
		}
		periodSeconds:    30
		failureThreshold: 3
		timeoutSeconds:   5
	}

	// -- Readiness probe
	readinessProbe: {
		httpGet: {
			path: "/rest/uuid"
			port: "http"
		}
		periodSeconds:    10
		failureThreshold: 5
		timeoutSeconds:   5
	}

	// =============================================================================
	// Prometheus Metrics
	// =============================================================================

	// -- Prometheus metrics configuration.
	// Requires the openHAB Metrics addon to be installed via the UI or marketplace.
	// Endpoint: /rest/metrics/prometheus (port 8080, no authentication required)
	// Addon docs: https://www.openhab.org/addons/integrations/metrics/
	metrics: {
		// -- Enable Prometheus metrics support
		enabled: false

		// -- Add classic Prometheus scrape annotations to the pod.
		// Works with annotation-based scraping (without Prometheus Operator).
		podAnnotations: {
			// -- Enable pod annotation-based scraping
			enabled: true
		}

		// -- Create a ServiceMonitor resource for Prometheus Operator.
		serviceMonitor: {
			// -- Enable ServiceMonitor creation
			enabled: false
			// -- Namespace for the ServiceMonitor (defaults to release namespace)
			namespace: ""
			// -- Scrape interval
			interval: "60s"
			// -- Scrape timeout
			scrapeTimeout: "10s"
			// -- Additional labels on the ServiceMonitor (e.g. to match your Prometheus selector)
			additionalLabels: {}
			// -- Additional relabelings
			relabelings: []
			// -- Metric relabelings
			metricRelabelings: []
		}
	}

	// =============================================================================
	// Automated Backups
	// =============================================================================

	// -- Automated backup configuration.
	// Creates a CronJob that tars openHAB data directories and uploads them to
	// an S3-compatible bucket using the MinIO client (mc).
	//
	// Directories backed up:
	//   - /openhab/userdata (always) - JSONDB, persistence data, rules state
	//   - /openhab/conf    (optional) - items, things, sitemaps, rules files
	//
	// Excluded from userdata backup (not needed for restore):
	//   - userdata/logs   - log files
	//   - userdata/tmp    - temporary files
	//   - userdata/cache  - OSGi bundle cache (rebuilt automatically on startup)
	backup: {
		// -- Enable automated backup CronJob
		enabled: false

		// -- Backup schedule in cron format
		schedule: "0 3 * * *"

		// -- Suspend the CronJob without deleting it
		suspend: false

		// -- CronJob concurrency policy
		concurrencyPolicy: "Forbid"

		// -- Successful job history to retain
		successfulJobsHistoryLimit: 3

		// -- Failed job history to retain
		failedJobsHistoryLimit: 3

		// -- Job backoff limit
		backoffLimit: 1

		// -- Prefix used in backup archive names: openhab-backup-<timestamp>.tar.gz
		archivePrefix: "openhab"

		// -- What to include in the backup
		include: {
			// -- Backup /openhab/userdata (JSONDB, persistence, rules state) - STRONGLY recommended
			userdata: true
			// -- Backup /openhab/conf (items, things, sitemaps, rules files)
			// Set to false if you manage conf entirely via ConfigMaps (GitOps)
			conf: true
		}

		images: {
			// -- Backup utility image (provides tar, gzip, cp)
			utility: {
				repository: "docker.io/library/alpine"
				tag:        "3.22"
				pullPolicy: "IfNotPresent"
			}
			// -- S3 uploader image (MinIO client)
			uploader: {
				repository: "docker.io/helmforge/mc"
				tag:        "1.0.0"
				pullPolicy: "IfNotPresent"
			}
		}

		// -- Resource requests/limits for backup containers
		resources: {
			requests: {
				cpu:    "100m"
				memory: "128Mi"
			}
			limits: {
				cpu:    "500m"
				memory: "256Mi"
			}
		}

		s3: {
			// -- S3-compatible endpoint URL (e.g. https://s3.amazonaws.com or https://minio.example.com)
			endpoint: ""
			// -- Target bucket name
			bucket: ""
			// -- Key prefix within the bucket
			prefix: "openhab"
			// -- S3 access key (stored in a Secret)
			accessKey: ""
			// -- S3 secret key (stored in a Secret)
			secretKey: ""
			// -- Use an existing Secret for S3 credentials (keys: access-key, secret-key)
			existingSecret: ""
		}
	}

	// =============================================================================
	// Scheduling & Node Affinity
	// =============================================================================

	// -- Node selector
	nodeSelector: {}

	// -- Tolerations
	tolerations: []

	// -- Affinity rules
	affinity: {}

	// -- Extra volumes (e.g. for custom addons from a hostPath)
	extraVolumes: []

	// -- Extra volume mounts
	extraVolumeMounts: []

	// -- Extra environment variables (as a list of name/value or name/valueFrom)
	extraEnv: []

	// =============================================================================
	// Gateway API & External Secrets
	// =============================================================================

	// ## Gateway API configuration (GR-060)
	gateway: {
		enabled: false
		hostnames: [
			"openhab.local",
		]
		parentRefs: []
	}

	// ## ExternalSecrets configuration (GR-061)
	externalSecrets: {
		enabled:         false
		apiVersion:      "external-secrets.io/v1"
		refreshInterval: "1h"
		secretStoreRef: {
			name: ""
			kind: "ClusterSecretStore"
		}
		target: {
			creationPolicy: "Owner"
		}
		data: []
	}
}
