// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.
// Reference: https://github.com/helmforgedev/charts/blob/main/charts/moodle/values.yaml

@if(!debug)

package main

// Defaults for Moodle mirroring Helm values.yaml.
values: {
	// -- Override the chart name.
	nameOverride: ""

	// -- Override resource names.
	fullnameOverride: ""

	// -- Additional resource labels; selector labels are reserved.
	commonLabels: {}

	// -- Number of web pods; multiple replicas require RWX and Redis sessions.
	replicaCount: 1

	// -- Official PHP/Apache runtime, separately pinned from the Moodle code.
	image: {
		// -- Image repository; custom images must contain the same PHP/Apache tools.
		repository: "docker.io/moodlehq/moodle-php-apache"
		// -- Human-readable PHP variant; digest pins the actual bytes.
		tag: "8.4-bookworm"
		// -- Multi-architecture manifest digest.
		digest: "sha256:922af51668352004b4255cdc1f726a63f0cee7c1354eaf66dd8d5f2c7cc379b5"
		// -- Container image pull policy.
		pullPolicy: "IfNotPresent"
	}

	// -- Registry credentials.
	imagePullSecrets: []

	// -- Immutable Moodle code distribution, prepared once per pod.
	source: {
		// -- archive downloads a verified release; image copies code baked into image.path.
		mode: "archive"
		// -- Official release archive or an HTTPS mirror of identical bytes.
		url: "https://download.moodle.org/download.php/direct/stable503/moodle-5.3.tgz"
		// -- SHA-256 of the archive; verified before extraction.
		sha256: "7e5edf110555956571f40e42acffde0eb23681ebebd212a2fec0fe7d795dd511"
		// -- Source directory in a custom image when mode=image.
		imagePath: "/opt/moodle"
		// -- Maximum HTTPS download time per attempt in seconds.
		downloadTimeout: 180
	}

	// -- Moodle application settings.
	moodle: {
		// -- Public URL without trailing slash. Set the real HTTPS URL in production.
		wwwroot: "http://localhost:8080"
		// -- Full site name used only on first installation.
		siteName: "Moodle Learning Platform"
		// -- Short site name used only on first installation.
		shortName: "Moodle"
		// -- Installation language. Non-English language packs require upstream egress.
		language: "en"
		// -- Administrative account name used only on first installation.
		adminUser: "admin"
		// -- Administrative contact email.
		adminEmail: "admin@example.com"
		// -- Inline bootstrap password; generated and preserved when empty.
		adminPassword: ""
		// -- Existing bootstrap secret. Password changes do not reset an installed account.
		existingSecret: ""
		// -- Bootstrap secret password key.
		existingSecretPasswordKey: "admin-password"
		// -- Enable automated first installation into an empty application database.
		autoInstall: true
		// -- Allow TLS termination at a trusted proxy; pair with HTTPS wwwroot.
		sslProxy: false
		// -- Enable only when proxy rewrites Host.
		reverseProxy: false
		// -- Disable browser-based plugin installation and code updates.
		disableUpdateAutodeploy: true
		// -- Disable outgoing email, useful in restored or staging environments.
		noEmailEver: false
		// -- Site timezone, configured consistently for PHP and Moodle.
		timezone: "UTC"
		// -- Additional config.php statements before Moodle setup; trusted administrator code.
		extraConfig: ""
		// -- Extra environment variables for PHP workloads, including cron.
		extraEnv: []
		// -- Extra environment sources for PHP workloads.
		extraEnvFrom: []
	}

	// -- Application database connection; disable every database subchart for an external server.
	database: {
		// -- Backend: postgresql, mysql or mariadb. Changing an installed site's backend requires a separate data migration.
		type: "postgresql"
		// -- External database hostname; ignored when the selected subchart is enabled.
		host: ""
		// -- External database port; zero selects 5432 for PostgreSQL or 3306 for MySQL/MariaDB.
		port: 0
		// -- External database name.
		name: "moodle"
		// -- External database user.
		username: "moodle"
		// -- External database password Secret, required when all database subcharts are disabled.
		existingSecret: ""
		// -- Password key in the external Secret.
		existingSecretPasswordKey: "password"
		// -- Moodle table prefix; at most ten alphanumeric/underscore characters.
		prefix: "mdl_"
		// -- PostgreSQL libpq SSL mode; use verify-full with a CA for external PostgreSQL.
		sslMode: "prefer"
		// -- MySQL/MariaDB TLS mode: disable, require (encryption only), or verify-full (CA and hostname).
		mysqlSslMode: "disable"
		// -- MySQL/MariaDB collation; Unicode utf8mb4 is required for full Moodle character support.
		collation: "utf8mb4_unicode_ci"
		// -- Optional Secret containing the database CA certificate.
		tlsSecret: ""
		// -- CA certificate key in database.tlsSecret.
		tlsCAKey: "ca.crt"
		// -- Maximum wait for authenticated DB connectivity and installer lock.
		connectTimeout: 180
	}

	// -- Bundled HelmForge PostgreSQL; full subchart values may be overridden.
	postgresql: {
		// -- Deploy PostgreSQL.
		enabled:          true
		architecture:     "standalone"
		fullnameOverride: ""
		image: {
			repository: "docker.io/library/postgres"
			tag:        "18.6-trixie"
			digest:     ""
			pullPolicy: "IfNotPresent"
		}
		// -- Database bootstrap credentials.
		auth: {
			database:                          "moodle"
			username:                          "moodle"
			password:                          ""
			postgresPassword:                  ""
			existingSecret:                    ""
			existingSecretUserPasswordKey:     "user-password"
			existingSecretPostgresPasswordKey: "postgres-password"
		}
		resources: {
			requests: {cpu: "250m", memory: "512Mi"}
			limits: {cpu: "500m", memory: "1Gi"}
		}
		podSecurityContext: {
			fsGroup:             999
			fsGroupChangePolicy: "OnRootMismatch"
			seccompProfile: type: "RuntimeDefault"
		}
		securityContext: {
			allowPrivilegeEscalation: false
			readOnlyRootFilesystem:   false
			runAsNonRoot:             true
			runAsUser:                999
			runAsGroup:               999
			capabilities: drop: ["ALL"]
		}
		persistence: {
			enabled:      true
			storageClass: ""
			accessModes: ["ReadWriteOnce"]
			size: "8Gi"
		}
	}

	// -- Bundled HelmForge MySQL; full subchart values may be overridden.
	mysql: {
		// -- Deploy MySQL; requires database.type=mysql and the other database subcharts disabled.
		enabled:          false
		architecture:     "standalone"
		fullnameOverride: ""
		image: {
			repository: "docker.io/library/mysql"
			tag:        "8.4"
			digest:     ""
			pullPolicy: "IfNotPresent"
		}
		auth: {
			database:                             "moodle"
			username:                             "moodle"
			password:                             ""
			rootPassword:                         ""
			replicationPassword:                  ""
			existingSecret:                       ""
			existingSecretUserPasswordKey:        "mysql-user-password"
			existingSecretRootPasswordKey:        "mysql-root-password"
			existingSecretReplicationPasswordKey: "mysql-replication-password"
		}
		resources: {
			requests: {cpu: "250m", memory: "512Mi"}
			limits: {cpu: "500m", memory: "1Gi"}
		}
		podSecurityContext: {
			fsGroup:             999
			fsGroupChangePolicy: "OnRootMismatch"
			seccompProfile: type: "RuntimeDefault"
		}
		securityContext: {
			allowPrivilegeEscalation: false
			readOnlyRootFilesystem:   false
			runAsNonRoot:             true
			runAsUser:                999
			runAsGroup:               999
			capabilities: drop: ["ALL"]
		}
		persistence: {
			enabled:      true
			storageClass: ""
			accessModes: ["ReadWriteOnce"]
			size: "8Gi"
		}
	}

	// -- Bundled HelmForge MariaDB; full subchart values may be overridden.
	mariadb: {
		// -- Deploy MariaDB; requires database.type=mariadb and the other database subcharts disabled.
		enabled:          false
		architecture:     "standalone"
		fullnameOverride: ""
		image: {
			repository: "docker.io/library/mariadb"
			tag:        "11.8"
			digest:     ""
			pullPolicy: "IfNotPresent"
		}
		auth: {
			database:                             "moodle"
			username:                             "moodle"
			password:                             ""
			rootPassword:                         ""
			replicationPassword:                  ""
			existingSecret:                       ""
			existingSecretUserPasswordKey:        "mariadb-user-password"
			existingSecretRootPasswordKey:        "mariadb-root-password"
			existingSecretReplicationPasswordKey: "mariadb-replication-password"
		}
		resources: {
			requests: {cpu: "250m", memory: "512Mi"}
			limits: {cpu: "500m", memory: "1Gi"}
		}
		podSecurityContext: {
			fsGroup:             999
			fsGroupChangePolicy: "OnRootMismatch"
			seccompProfile: type: "RuntimeDefault"
		}
		securityContext: {
			allowPrivilegeEscalation: false
			readOnlyRootFilesystem:   false
			runAsNonRoot:             true
			runAsUser:                999
			runAsGroup:               999
			capabilities: drop: ["ALL"]
		}
		persistence: {
			enabled:      true
			storageClass: ""
			accessModes: ["ReadWriteOnce"]
			size: "8Gi"
		}
	}

	// -- Redis session options; independent of Moodle MUC cache mappings.
	sessions: {
		// -- Use Redis sessions; requires bundled Redis or an external Redis endpoint.
		enabled:                   true
		host:                      ""
		port:                      6379
		database:                  0
		prefix:                    "moodle_session_"
		existingSecret:            ""
		existingSecretPasswordKey: "redis-password"
		tlsSecret:                 ""
		tlsCAKey:                  "ca.crt"
		acquireLockTimeout:        120
		lockExpire:                7200
	}

	// -- Optional HelmForge Redis subchart for sessions.
	redis: {
		// -- Deploy Redis; also set sessions.enabled=true.
		enabled:          true
		architecture:     "standalone"
		fullnameOverride: ""
		image: {
			repository: "docker.io/valkey/valkey"
			tag:        "9.2"
			digest:     ""
			pullPolicy: "IfNotPresent"
		}
		auth: {
			enabled:                   true
			password:                  ""
			existingSecret:            ""
			existingSecretPasswordKey: "redis-password"
		}
		resources: {
			requests: {cpu: "100m", memory: "128Mi"}
			limits: {cpu: "500m", memory: "512Mi"}
		}
		podSecurityContext: {
			fsGroup:             999
			fsGroupChangePolicy: "OnRootMismatch"
			seccompProfile: type: "RuntimeDefault"
		}
		securityContext: {
			allowPrivilegeEscalation: false
			readOnlyRootFilesystem:   false
			runAsNonRoot:             true
			runAsUser:                999
			runAsGroup:               999
			capabilities: drop: ["ALL"]
		}
		persistence: {
			enabled:      true
			storageClass: ""
			accessModes: ["ReadWriteOnce"]
			size: "8Gi"
		}
	}

	// -- Persistent Moodle data, always outside the web root.
	persistence: {
		// -- Enable persistent moodledata. Disable only for disposable tests.
		enabled:       true
		existingClaim: ""
		storageClass:  ""
		// -- Use ReadWriteMany for multiple web replicas.
		accessModes: ["ReadWriteOnce"]
		// -- Requested data capacity.
		size:   "10Gi"
		retain: true
		// -- Additional PVC annotations.
		annotations: {}
	}

	// -- PHP runtime configuration.
	php: {
		// -- Memory limit for each PHP process; align with pod concurrency/resources.
		memoryLimit:       "256M"
		uploadMaxFilesize: "64M"
		postMaxSize:       "64M"
		maxInputVars:      5000
		maxExecutionTime:  300
		extraIni:          ""
	}

	// -- Apache prefork concurrency; each child may consume php.memoryLimit.
	apache: {
		// -- Maximum concurrent PHP requests per web pod.
		maxRequestWorkers: 8
	}

	// -- Cron sidecar shares code and data with its web pod, including RWO storage.
	cron: {
		// -- Run scheduled Moodle tasks; Moodle database locks coordinate multiple pods.
		enabled:  true
		interval: 60
		resources: {
			requests: {cpu: "100m", memory: "256Mi"}
			limits: {cpu: "1", memory: "1Gi"}
		}
	}

	// -- Additional ad-hoc task processing in a separate sidecar.
	adhoc: {
		// -- Enable a dedicated ad-hoc worker; normal cron already handles ad-hoc tasks.
		enabled:   false
		keepAlive: 55
		resources: {
			requests: {cpu: "100m", memory: "256Mi"}
			limits: {cpu: "1", memory: "1Gi"}
		}
	}

	// -- Explicit maintenance window; stops web/task pods before running an operator-requested job.
	maintenance: {
		// -- Scale web pods to zero and run the selected maintenance action.
		enabled:               false
		runId:                 "manual-1"
		action:                "checks"
		activeDeadlineSeconds: 1800
	}

	// -- Optional authenticated Moodle application metrics through tool_monitoring.
	metrics: {
		// -- Install/configure the plugin and expose a private metrics listener.
		enabled:                false
		existingSecret:         ""
		existingSecretTokenKey: "token"
		plugin: {
			mode:   "archive"
			url:    "https://codeload.github.com/daniil-berg/moodle-tool_monitoring/tar.gz/23c45f66b6c3ed409b0749017b3387c1744016cc"
			sha256: "dc7a5256e93e10b0514fcb752767e2554b7aa0cd24e8c8d74e54c33b358028e1"
		}
		enabledMetrics: ["courses", "overdue_tasks", "quiz_attempts_in_progress", "user_accounts", "users_online"]
		serviceMonitor: {
			enabled:           false
			labels: {}
			annotations: {}
			interval:          "60s"
			scrapeTimeout:     "20s"
			relabelings: []
			metricRelabelings: []
		}
		prometheusRule: {
			enabled:         false
			labels: {}
			unavailableFor:  "5m"
			overdueTasksFor: "15m"
		}
	}

	// -- Outbound SMTP settings.
	smtp: {
		hosts:                     ""
		security:                  "tls"
		username:                  ""
		existingSecret:            ""
		existingSecretPasswordKey: "smtp-password"
		noReplyAddress:            "noreply@example.com"
	}

	// -- Web container resources.
	resources: {
		requests: {cpu: "250m", memory: "512Mi"}
		limits: {cpu: "2", memory: "2Gi"}
	}

	// -- Source preparation and installation resources.
	initResources: {
		requests: {cpu: "250m", memory: "256Mi"}
		limits: {cpu: "2", memory: "1Gi"}
	}

	// -- Pod filesystem ownership and seccomp.
	podSecurityContext: {
		runAsUser:           33
		runAsGroup:          33
		runAsNonRoot:        true
		fsGroup:             33
		fsGroupChangePolicy: "OnRootMismatch"
		seccompProfile: type: "RuntimeDefault"
	}

	// -- Container hardening applied to web, init, cron and worker.
	securityContext: {
		allowPrivilegeEscalation: false
		readOnlyRootFilesystem:   true
		capabilities: drop: ["ALL"]
	}

	terminationGracePeriodSeconds: 120
	podLabels: {}
	podAnnotations: {}
	nodeSelector: {}
	tolerations: []
	affinity: {}
	topologySpreadConstraints: []
	priorityClassName:         ""
	extraVolumes: []
	extraVolumeMounts: []

	// -- Dedicated service account configuration.
	serviceAccount: {
		create:      true
		name:        ""
		annotations: {}
	}

	// -- Web service options.
	service: {
		type: "ClusterIP"
		port: 80
		annotations: {}
	}

	// -- Gateway API HTTPRoute exposure to an existing Gateway.
	gatewayAPI: {
		// -- Enable this capability.
		enabled: true
		// -- GatewayClass name.
		gatewayClassName: ""
		// -- Route definitions with parentRefs, hostnames, rules, labels and annotations.
		httpRoutes: [
			{
				name: ""
				// -- Route labels.
				labels: {}
				// -- Route annotations.
				annotations: {}
				// -- References to parent Gateways.
				parentRefs: [
					{
						// -- Gateway name.
						name: "shared-gtw"
						// -- Gateway namespace (optional, defaults to route namespace).
						namespace: "kube-system"
						// -- Gateway API group.
						group: "gateway.networking.k8s.io"
						// -- Gateway API kind.
						kind: "Gateway"
						// -- Gateway section name.
						sectionName: ""
						// -- Gateway listener port.
						port: 80
					},
				]
				// -- Hostnames matching the route.
				hostnames: []
				// -- Routing rules, match conditions, filters and backend references.
				rules: [
					{
						matches: [
							{
								path: {
									type:  "PathPrefix"
									value: "/"
								}
							},
						]
					},
				]
			},
		]
	}

	// -- Canonical External Secrets integration.
	externalSecrets: {
		enabled:         false
		refreshInterval: "1h"
		items: []
	}

	// -- Autoscaling requires shared data and Redis sessions.
	autoscaling: {
		enabled:                        false
		minReplicas:                    2
		maxReplicas:                    5
		targetCPUUtilizationPercentage: 70
	}

	// -- Voluntary disruption protection.
	pdb: {
		enabled:      false
		minAvailable: 1
	}
}
