// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.
// Reference: https://github.com/CollaboraOnline/online/blob/main/kubernetes/helm/collabora-online/values.yaml
// https://github.com/trueforge-org/truecharts/blob/master/charts/stable/collabora/values.yaml
@if(!debug)

package main

// Defaults
values: {
	image: {
		repository: "docker.io/collabora/code"
		pullPolicy: "IfNotPresent"
		tag:        "26.04.4.1.1"
		digest:     "sha256:1efda3043e8b9cb437d1b6c6efe20cc3753760e634de012b8dac391da488bf97"
	}

	imagePullSecrets: []
	nameOverride:     ""
	fullnameOverride: ""
	terminationGracePeriodSeconds: 60

	serviceAccount: {
		create:      true
		annotations: {}
		name:        ""
	}

	daemonSetServiceAccount: {
		create:      true
		annotations: {}
		name:        ""
	}

	collabora: {
		aliasgroups: []
		aliasgroup1: "https://cloud.example.com"
		extra_params: "--o:ssl.enable=false --o:ssl.termination=true --o:welcome.enable=false --o:mount_jail_tree=false --o:user_interface.mode=default"
		server_name:  "example.com"
		existingSecret: {
			enabled:     false
			secretName:  ""
			usernameKey: "username"
			passwordKey: "password"
		}
		password: "changeme"
		username: "admin"
		env: []
		proofKeysSecretRef: ""
		proofKeyGeneration: {
			enabled:    false
			secretName: ""
		}
		coolkitconfig_xcu_content: ""
		coolwsd_xml_content:       ""
		dictionaries: [
			"de_DE",
			"en_GB",
			"en_US",
			"el_GR",
			"es_ES",
			"fr_FR",
			"pt_BR",
			"pt_PT",
			"it",
			"nl",
			"ru",
		]
		interface:       "default"
		ssl_enable:      false
		ssl_termination: true
		no_gen_ssl:      true
	}

	prometheus: {
		servicemonitor: {
			enabled: false
			labels: {}
		}
		rules: {
			enabled:          false
			additionalLabels: {}
			defaults: {
				enabled: true
				docs: {
					duplicated: 0
					pod: {
						critical: 10
						warning:  8
						info:     5
					}
					sum: {
						critical: 500
						warning:  200
						info:     50
					}
				}
				errorServiceUnavailable: {
					critical: 50
					warning:  2
					info:     0
				}
				errorUnauthorizedRequest: {
					observationInterval: "60m"
					eventCounter:        8
				}
				errorStorageConnections: {
					critical: 50
					warning:  2
					info:     0
				}
				viewers: {
					pod: {
						critical: 100
						warning:  80
						info:     60
					}
					doc: {
						critical: 50
						warning:  40
						info:     30
					}
					sum: {
						critical: 15000
						warning:  12000
						info:     5000
					}
				}
			}
			additionalRules: []
		}
	}

	grafana: {
		dashboards: {
			enabled: true
			labels: {
				grafana_dashboard: "1"
			}
			annotations: {}
		}
	}

	logging: {
		enabled:           false
		ecs:               false
		additionalFilters: []
		localOutputRefs: []
		globalOutputRefs: [
			"default",
		]
	}

	podAnnotations: {}
	podLabels: {}

	podSecurityContext: {
		fsGroup: 1001
		fsGroupChangePolicy: "OnRootMismatch"
		seccompProfile: {
			type: "RuntimeDefault"
		}
	}

	installCOOLSeccompProfile: false

	securityContext: {
		readOnlyRootFilesystem:   false
		privileged: false
		capabilities: {
			drop: [
				"ALL"
			]
		}
		runAsNonRoot:             true
		runAsUser:                1001
		allowPrivilegeEscalation: false
		seccompProfile: {
			type: "RuntimeDefault"
		}
	}

	service: {
		type: "ClusterIP"
		port: 9980
		annotations: {}
	}

	deployment: {
		kind:            "Deployment"
		annotations: {}
		labels: {}
		containerPort:   9980
		type:            "RollingUpdate"
		minReadySeconds: 0
		maxUnavailable:  0
		maxSurge:        1
		customFonts: {
			enabled: false
			pvc: {
				size:       "1Gi"
				accessMode: "ReadWriteOnce"
			}
			image: {
				repository: "docker.io/alpine"
				tag:        "3.22.0"
			}
			securityContext: {
				runAsUser: 1001
				allowPrivilegeEscalation: false
				privileged: false
				readOnlyRootFilesystem: false
				seccompProfile: {
					type: "RuntimeDefault"
				}
				capabilities: {
					drop: [
						"ALL"
					]
				}
			}
        }
	}

	probes: {
		scheme: ""
		startup: {
			enabled:          true
			failureThreshold: 30
			periodSeconds:    3
			path:             "/"
		}
		readiness: {
			enabled:             true
			initialDelaySeconds: 0
			periodSeconds:       10
			timeoutSeconds:      30
			successThreshold:    1
			failureThreshold:    2
			path:                "/"
		}
		liveness: {
			enabled:             true
			initialDelaySeconds: 0
			periodSeconds:       10
			timeoutSeconds:      30
			successThreshold:    1
			failureThreshold:    4
			path:                "/"
		}
	}

	route: {
		enabled:    true
		apiVersion: "gateway.networking.k8s.io/v1"
		kind:       "HTTPRoute"
		annotations: {}
		labels: {}
		hostnames: []
		parentRefs: [{
			name:      "shared-gtw"
			namespace: "kube-system"
		}]
		path:     "/"
		pathType: "PathPrefix"
		matches: [{
			path: {
				type:  "PathPrefix"
				value: "/"
			}
		}]
		filters: []
		additionalRules: []
	}

	ingress: {
		enabled:   false
		className: ""
		annotations: {}
		hosts: [{
			host: "chart-example.local"
			paths: [{
				path:     "/"
				pathType: "ImplementationSpecific"
			}]
		}]
		tls: []
	}

	resources: {
		requests: {
			cpu:    "75m"
			memory: "200Mi"
		}
		limits: {
			cpu:    "1500m"
			memory: "2400Mi"
		}
	}

	replicaCount: 1
	replicas:     1

	autoscaling: {
		enabled:                           true
		minReplicas:                       2
		maxReplicas:                       3
		targetCPUUtilizationPercentage:    70
		targetMemoryUtilizationPercentage: 50
		scaleDownDisabled:                 false
	}

	networkPolicy: {
		enabled: false
	}

	podDisruptionBudget: {
		enabled: true
	}

	nginxDeny: {
		enabled: false
		image: {
			repository: "docker.io/nginx"
			tag:        "stable-alpine"
			pullPolicy: "IfNotPresent"
		}
		replicaCount:  1
		podAnnotations: {}
		podSecurityContext: {}
		securityContext: {}
		containerPort: 80
		env: []
		resources: {}
		nodeSelector: {}
		tolerations: []
		affinity: {}
		service: {
			port: 8080
		}
		ingress: {
			enabled:   false
			className: ""
			annotations: {}
			hosts: [{
				host: "chart-example.local"
				paths: [{
					path:     "/"
					pathType: "ImplementationSpecific"
				}]
			}]
			tls: []
		}
	}

	reverseProxy: {
		enabled: false
		image: {
			repository: "docker.io/nginxinc/nginx-unprivileged"
			tag:        "stable"
			pullPolicy: "IfNotPresent"
		}
		replicaCount:  1
		containerPort: 8080
		hashParam:     "WOPISrc"
		upstreamPort:  9980
		proxyTimeout:  "3600s"
		controller: {
			enabled:  false
			upstream: ""
		}
		nginxConfigOverride: ""
		endpointReloader: {
			enabled: true
			image: {
				repository: "docker.io/alpine/k8s"
				tag:        "1.31.1"
				pullPolicy: "IfNotPresent"
			}
		}
		podAnnotations: {}
		podSecurityContext: {
			runAsNonRoot: true
			seccompProfile: {
				type: "RuntimeDefault"
			}
		}
		securityContext: {
			allowPrivilegeEscalation: false
			readOnlyRootFilesystem:   false
			runAsNonRoot:             true
			capabilities: {
				drop: ["ALL"]
			}
			seccompProfile: {
				type: "RuntimeDefault"
			}
		}
		resources: {}
		nodeSelector: {}
		tolerations: []
		affinity: {}
		service: {
			type: "ClusterIP"
			port: 8080
		}
		route: {
			enabled: false
			host:    ""
			annotations: {
				"haproxy.router.openshift.io/timeout": "3600s"
			}
			tls: {}
		}
		ingress: {
			enabled:   false
			className: ""
			annotations: {}
			hosts: [{
				host: "chart-example.local"
				paths: [{
					path:     "/"
					pathType: "ImplementationSpecific"
				}]
			}]
			tls: []
		}
	}

	dynamicConfig: {
		enabled:       false
		configuration: "{}"
		logging: {
			enabled:           false
			ecs:               false
			additionalFilters: []
			localOutputRefs: []
			globalOutputRefs: [
				"default",
			]
		}
		image: {
			repository: "docker.io/nginx"
			tag:        "1.25"
			pullPolicy: "IfNotPresent"
		}
		replicaCount:  1
		podAnnotations: {}
		podSecurityContext: {}
		securityContext: {}
		existingConfigMap: {
			enabled: false
			name:    ""
		}
		upload: {
			enabled: false
			image: {
				repository: "docker.io/twostoryrobot/simple-file-upload"
				tag:        "latest"
				digest:     "sha256:547fc4360b31d8604b7a26202914e87cd13609cc938fd83f412c77eb44aa1cc4"
			}
			key: "TESTKEY"
			pvc: {
				size:       "1Gi"
				accessMode: "ReadWriteOnce"
			}
			service: {
				port: 8090
			}
			ingress: {
				enabled:   false
				className: ""
				annotations: {}
				hosts: [{
					host: "chart-example.local"
					paths: [{
						path:     "/"
						pathType: "ImplementationSpecific"
					}]
				}]
				tls: []
			}
			logging: {
				enabled:           false
				ecs:               false
				additionalFilters: []
				localOutputRefs: []
				globalOutputRefs: [
					"default",
				]
			}
		}
		containerPort: 80
		probes: {
			scheme: "HTTP"
			startup: {
				enabled:          true
				failureThreshold: 30
				periodSeconds:    2
			}
			readiness: {
				enabled:             true
				initialDelaySeconds: 0
				periodSeconds:       10
				timeoutSeconds:      30
				successThreshold:    1
				failureThreshold:    2
			}
			liveness: {
				enabled:             true
				initialDelaySeconds: 0
				periodSeconds:       10
				timeoutSeconds:      30
				successThreshold:    1
				failureThreshold:    4
			}
		}
		env: []
		resources: {}
		nodeSelector: {}
		tolerations: []
		affinity: {}
		service: {
			port: 8080
		}
		ingress: {
			enabled:   false
			className: ""
			annotations: {}
			hosts: [{
				host: "chart-example.local"
				paths: [{
					path:     "/"
					pathType: "ImplementationSpecific"
				}]
			}]
			tls: []
		}
	}

	trusted_certs_install: {
		enabled:       false
		trusted_certs: []
	}

	priorityClassName: ""

	nodeSelector: {
		"kubernetes.io/arch": "amd64"
	}

	tolerations: []
	affinity: {
		podAntiAffinity: "soft"
	}

	extraVolumes:      []
	extraVolumeMounts: []
	extraEnvVars: [
		{name: "DONT_GEN_SSL_CERT", value: "true"},
		{name: "dictionaries", value: "de_DE en_GB en_US el_GR es_ES fr_FR pt_BR pt_PT it nl ru"},
		{name: "TZ", value: "UTC"},
		{name: "UMASK", value: "0022"},
		{name: "UMASK_SET", value: "0022"},
		{name: "NVIDIA_VISIBLE_DEVICES", value: "void"},
		{name: "S6_READ_ONLY_ROOT", value: "1"},
	]

	extraObjects: []
}
