// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(debug)

package main

// Defaults
values: {
	image: {
		pullPolicy: "IfNotPresent"
		repository: "ghcr.io/mriedmann/humhub-phponly"
		tag:        "1.17.2@sha256:3f00ef2b0ef98b4665acdad27f7f0c40325391182193bdb783c64e26a9b94b2c"
	}
	nginxImage: {
		pullPolicy: "IfNotPresent"
		repository: "ghcr.io/mriedmann/humhub-nginx"
		tag:        "1.17.2@sha256:47fb119e2e0a182546a93646efcb5cd3f480171398eb1551b31e2030ec93c578"
	}

	securityContext: {
		container: {
			runAsNonRoot:           false
			readOnlyRootFilesystem: false
			runAsUser:              0
			runAsGroup:             0
		}
	}

	resources: {
		requests: {
			cpu:    "75m"
			memory: "200Mi"
		}
		limits: {
			cpu:    "1500m"
			memory: "2400Mi"
		}
	}
	initResources: {
		requests: {
			cpu:    "10m"
			memory: "50Mi"
		}
		limits: {
			cpu:    "500m"
			memory: "512Mi"
		}
	}

	service: {
		main: {
			targetSelector: "nginx"
			ports: {
				main: {
					protocol:       "http"
					targetSelector: "nginx"
					targetPort:     80
					port:           8080
				}
			}
		}
		backend: {
			enabled:        true
			type:           "ClusterIP"
			targetSelector: "main"
			ports: {
				backend: {
					enabled:        true
					targetPort:     9000
					targetSelector: "main"
					port:           9000
				}
			}
		}
	}

	humhub: {
		nginx: {
			max_client_body_size: "10m"
			keep_alive_timeout:   65
		}
		proto: "http"
		host:  "localhost:8080"
		admin: {
			login:    "admin"
			password: "test"
			email:    "humhub@example.com"
		}
		mailer: {
			sys_address:           "noreply@example.com"
			sys_name:              "HumHub"
			type:                  "smtp"
			hostname:              ""
			port:                  1025
			user:                  ""
			password:              ""
			encrypt:               ""
			allow_self_sign_certs: false
		}
	}

	workload: {
		main: {
			podSpec: {
				containers: {
					main: {
						probes: {
							liveness: {
								enabled: true
								type:    "exec"
								command: "/usr/local/bin/php-fpm-healthcheck"
							}
							readiness: {
								enabled: true
								type:    "exec"
								command: "/usr/local/bin/php-fpm-healthcheck"
							}
							startup: {
								enabled: true
								type:    "exec"
								command: "/usr/local/bin/php-fpm-healthcheck"
							}
						}
						env: {
							HUMHUB_AUTO_INSTALL:    true
							HUMHUB_INTEGRITY_CHECK: true
							WAIT_FOR_DB:            true
							// Database
							HUMHUB_DB_USER:     "{{ .Values.mariadb.mariadbUsername }}"
							HUMHUB_DB_NAME:     "{{ .Values.mariadb.mariadbDatabase }}"
							HUMHUB_DB_PASSWORD: "{{ .Values.mariadb.password }}"
							HUMHUB_DB_HOST: {
								secretKeyRef: {
									expandObjectName: false
									name:             "{{ printf \"%s-%s\" .Release.Name \"mariadbcreds\" }}"
									key:              "plainhost"
								}
							}
							// Redis
							HUMHUB_QUEUE_CLASS:       "humhub\\modules\\queue\\driver\\Redis"
							HUMHUB_CACHE_CLASS:       "yii\\redis\\Cache"
							HUMHUB_CACHE_EXPIRE_TIME: 3600
							HUMHUB_REDIS_PORT:        6379
							HUMHUB_REDIS_HOSTNAME: {
								secretKeyRef: {
									expandObjectName: false
									name:             "{{ printf \"%s-%s\" .Release.Name \"rediscreds\" }}"
									key:              "plainhost"
								}
							}
							HUMHUB_REDIS_PASSWORD: "{{ .Values.redis.password }}"
							// Mailer
							HUMHUB_MAILER_SYSTEM_EMAIL_ADDRESS:    "{{ .Values.humhub.mailer.sys_address }}"
							HUMHUB_MAILER_SYSTEM_EMAIL_NAME:       "HumHub"
							HUMHUB_MAILER_TRANSPORT_TYPE:          "smtp"
							HUMHUB_MAILER_HOSTNAME:                "{{ .Values.humhub.mailer.hostname }}"
							HUMHUB_MAILER_PORT:                    "{{ .Values.humhub.mailer.port }}"
							HUMHUB_MAILER_USERNAME:                "{{ .Values.humhub.mailer.user }}"
							HUMHUB_MAILER_PASSWORD:                "{{ .Values.humhub.mailer.password }}"
							HUMHUB_MAILER_ENCRYPTION:              "{{ .Values.humhub.mailer.encrypt }}"
							HUMHUB_MAILER_ALLOW_SELF_SIGNED_CERTS: "{{ .Values.humhub.mailer.allow_self_sign_certs }}"
							// -- Initial install only
							// HTTP/HTTPS configuration
							HUMHUB_PROTO: "{{ .Values.humhub.proto }}"
							HUMHUB_HOST:  "{{ .Values.humhub.host }}"
							// -- Initial install only
							// Admin creattion
							HUMHUB_ADMIN_LOGIN:    "{{ .Values.humhub.admin.login }}"
							HUMHUB_ADMIN_EMAIL:    "{{ .Values.humhub.admin.email }}"
							HUMHUB_ADMIN_PASSWORD: "{{ .Values.humhub.admin.password }}"
						}
					}
				}
			}
		}
		nginx: {
			enabled: true
			type:    "Deployment"
			podSpec: {
				containers: {
					nginx: {
						enabled:       true
						primary:       true
						imageSelector: "nginxImage"
						env: {
							NGINX_CLIENT_MAX_BODY_SIZE: "{{ .Values.humhub.nginx.max_client_body_size }}"
							NGINX_KEEPALIVE_TIMEOUT:    "{{ .Values.humhub.nginx.keep_alive_timeout }}"
							NGINX_UPSTREAM:             "{{ printf \"%s-backend:9000\" (include \"tc.v1.common.lib.chart.names.fullname\" $) }}"
							// Allow IPs for `/ping` ONLY
							HUMHUB_REVERSEPROXY_WHITELIST: "10.0.0.0/8;172.16.0.0/16;192.168.0.0/24"
						}
						probes: {
							liveness: {
								enabled: true
								type:    "http"
								path:    "/ping"
								port:    80
							}
							readiness: {
								enabled: true
								type:    "http"
								path:    "/ping"
								port:    80
							}
							startup: {
								enabled: true
								type:    "tcp"
								port:    80
							}
						}
					}
				}
			}
		}
	}

	persistence: {
		config: {
			enabled:   true
			mountPath: "/var/www/localhost/htdocs/protected/config"
		}
		assets: {
			enabled:   true
			mountPath: "/var/www/localhost/htdocs/assets"
			targetSelector: {
				main: main: mountPath: "/var/www/localhost/htdocs/assets"
				nginx: nginx: mountPath: "/var/www/localhost/htdocs/assets"
			}
		}
		themes: {
			enabled:   true
			mountPath: "/var/www/localhost/htdocs/themes"
			targetSelector: {
				main: main: mountPath: "/var/www/localhost/htdocs/themes"
				nginx: nginx: mountPath: "/var/www/localhost/htdocs/themes"
			}
		}
		modules: {
			enabled: true
			targetSelector: {
				main: main: mountPath: "/var/www/localhost/htdocs/protected/modules"
				nginx: nginx: mountPath: "/var/www/localhost/htdocs/protected/modules"
			}
		}
		uploads: {
			enabled: true
			targetSelector: {
				main: main: mountPath: "/var/www/localhost/htdocs/uploads"
				nginx: nginx: mountPath: "/var/www/localhost/htdocs/uploads"
			}
		}
	}

	mariadb: {
		enabled:         true
		mariadbUsername: "humhub"
		mariadbDatabase: "humhub"
		image: {
			repository: "docker.io/bitnamisecure/mariadb"
			tag:        "latest@sha256:16c4d59ca1e33e557e5003596d244aefac4dd03220c8967ae12e3cee2a4c7dd9"
			pullPolicy: "IfNotPresent"
		}
		waitImage: {
			repository: "oci.trueforge.org/containerforge/mariadb-client"
			tag:        "12.3.3@sha256:fc2f5a8787aa02c7cbc25103f8b97e6a03d492d1516e3ecc8b30a0939af1b718"
			pullPolicy: "IfNotPresent"
		}
		securityContext: {
			fsGroup:             568
			fsGroupChangePolicy: "OnRootMismatch"
			container: {
				runAsUser:                568
				runAsGroup:               0
				runAsNonRoot:             false
				readOnlyRootFilesystem:   false
				allowPrivilegeEscalation: false
				privileged:               false
			}
			capabilities: {
				add: []
				drop: ["ALL"]
			}
		}
		resources: {
			requests: {
				cpu:    "75m"
				memory: "200Mi"
			}
			limits: {
				cpu:    "1500m"
				memory: "2400Mi"
			}
		}
	}

	redis: {
		enabled: true
		image: {
			repository: "docker.io/bitnamisecure/valkey"
			tag:        "latest@sha256:b330d587970c5925265a12d367feba4b6cd89078c75ba118ffb70002834c1a7c"
			pullPolicy: "IfNotPresent"
		}
		waitImage: {
			repository: "oci.trueforge.org/containerforge/valkey-tools"
			tag:        "1.1.0@sha256:7c2c18f0feeaa391d662a508c2d11fbb4cc7b5f1b07ff034ceb02a61df28db1d"
			pullPolicy: "IfNotPresent"
		}
		securityContext: {
			fsGroup:             568
			fsGroupChangePolicy: "OnRootMismatch"
			container: {
				runAsUser:                568
				runAsGroup:               0
				runAsNonRoot:             false
				readOnlyRootFilesystem:   false
				allowPrivilegeEscalation: false
				privileged:               false
			}
			capabilities: {
				add: []
				drop: ["ALL"]
			}
		}
		resources: {
			requests: {
				cpu:    "75m"
				memory: "200Mi"
			}
			limits: {
				cpu:    "1500m"
				memory: "2400Mi"
			}
		}
	}
}
