// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.
// Reference: https://github.com/helmforgedev/charts/blob/main/charts/middleware/values.yaml
@if(!debug)

package main

// Defaults
values: {
	nameOverride:     ""
	fullnameOverride: ""
	commonLabels: {}

	// =============================================================================
	// Image
	// =============================================================================

	image: {
		// -- Middleware container image
		repository: "docker.io/middlewareeng/middleware"
		// -- Image tag
		tag: "0.3.1"
		// -- Image digest
		digest: ""
		// -- Image pull policy
		pullPolicy: "IfNotPresent"
	}

	imagePullSecrets: []

	// =============================================================================
	// Middleware Configuration
	// =============================================================================

	middleware: {
		// -- Frontend port (Next.js)
		frontendPort: 3333
		// -- Analytics API port
		analyticsPort: 9696
		// -- Sync server port
		syncPort: 9697
		// -- Environment
		environment: "prod"
		// -- Disable internal PostgreSQL (use subchart instead)
		internalDbEnabled: "false"
		// -- Disable internal Redis (use subchart instead)
		internalRedisEnabled: "false"
		// -- Timezone
		timezone: "UTC"
		// -- Extra environment variables for the container
		extraEnv: []
	}

	// =============================================================================
	// External Database (when not using subchart)
	// =============================================================================

	externalDatabase: {
		// -- Use external database instead of subchart
		enabled: false
		// -- Database host
		host: ""
		// -- Database port
		port: 5432
		// -- Database name
		name: "mhq-oss"
		// -- Database user
		user: "middleware"
		// -- Database password
		password: ""
		// -- Existing secret with database credentials
		existingSecret: ""
		// -- Key in existing secret for password
		existingSecretPasswordKey: "user-password"
	}

	// =============================================================================
	// External Redis (when not using subchart)
	// =============================================================================

	externalRedis: {
		// -- Use external Redis instead of subchart
		enabled: false
		// -- Redis host
		host: ""
		// -- Redis port
		port: 6379
	}

	// =============================================================================
	// Persistence
	// =============================================================================

	persistence: {
		// -- Enable persistence for /app/keys
		enabled: true
		// -- Storage size
		size: "1Gi"
		// -- Storage class
		storageClass: ""
		// -- Access modes
		accessModes: [
			"ReadWriteOnce",
		]
		// -- Use an existing PVC
		existingClaim: ""
	}

	// =============================================================================
	// Service Account
	// =============================================================================

	serviceAccount: {
		// -- Create a ServiceAccount
		create: true
		// -- ServiceAccount name
		name: ""
		// -- Annotations for the ServiceAccount
		annotations: {}
		// -- Automount API credentials for a Service Account
		automountServiceAccountToken: false
	}

	// =============================================================================
	// Service
	// =============================================================================

	service: {
		// -- Service type
		type: "ClusterIP"
		// -- Frontend service port
		port: 80
		// -- Annotations for the Service
		annotations: {}
	}

	// =============================================================================
	// Ingress
	// =============================================================================

	ingress: {
		// -- Enable ingress for Middleware
		enabled: false
		// -- Ingress class name (for example: traefik, nginx)
		ingressClassName: "traefik"
		// -- Ingress annotations
		annotations: {}
		// -- Ingress hosts
		hosts: []
		// -- Ingress TLS configuration
		tls: []
	}

	// -- Gateway API HTTPRoute exposure to an existing Gateway.
	gatewayAPI: {
		// -- Enable this capability.
		enabled: true
		// -- GatewayClass name.
		gatewayClassName: ""
		// -- Route definitions with parentRefs, hostnames, rules, labels and annotations.
		httpRoutes: [
			{
				name: ""
				// -- Route labels.
				labels: {}
				// -- Route annotations.
				annotations: {}
				// -- References to parent Gateways.
				parentRefs: [
					{
						// -- Gateway name.
						name: "shared-gtw"
						// -- Gateway namespace (optional, defaults to route namespace).
						namespace: "kube-system"
						// -- Gateway API group.
						group: "gateway.networking.k8s.io"
						// -- Gateway API kind.
						kind: "Gateway"
						// -- Gateway section name.
						sectionName: ""
						// -- Gateway listener port.
						port: 80
					},
				]
				// -- Hostnames matching the route.
				hostnames: []
				// -- Routing rules, match conditions, filters and backend references.
				rules: [
					{
						matches: [
							{
								path: {
									type:  "PathPrefix"
									value: "/"
								}
							},
						]
					},
				]
			},
		]
	}

	// =============================================================================
	// Probes
	// =============================================================================

	probes: {
		startup: {
			enabled:             true
			initialDelaySeconds: 30
			periodSeconds:       5
			timeoutSeconds:      3
			failureThreshold:    30
		}
		liveness: {
			enabled:             true
			initialDelaySeconds: 0
			periodSeconds:       15
			timeoutSeconds:      5
			failureThreshold:    3
		}
		readiness: {
			enabled:             true
			initialDelaySeconds: 0
			periodSeconds:       10
			timeoutSeconds:      5
			failureThreshold:    3
		}
	}

	// =============================================================================
	// Resources and Security
	// =============================================================================

	resources: {
		requests: {
			cpu:    "250m"
			memory: "512Mi"
		}
		limits: {
			cpu:    "1"
			memory: "1Gi"
		}
	}

	podSecurityContext: {
		seccompProfile: type: "RuntimeDefault"
	}

	securityContext: {
		allowPrivilegeEscalation: false
		capabilities: drop: [
			"ALL",
		]
	}

	// =============================================================================
	// Scheduling
	// =============================================================================

	nodeSelector: {}
	tolerations: []
	affinity: {}
	topologySpreadConstraints: []
	priorityClassName:             ""
	terminationGracePeriodSeconds: 30

	podLabels: {}
	podAnnotations: {}

	// =============================================================================
	// Extra
	// =============================================================================

	extraVolumes: []
	extraVolumeMounts: []

	// -- Extra manifests to deploy alongside the module
	extraManifests: []

	// =============================================================================
	// PostgreSQL Subchart
	// =============================================================================

	postgresql: {
		// -- Enable bundled PostgreSQL
		enabled: true
		// -- PostgreSQL container image
		image: {
			repository: "docker.io/library/postgres"
			tag:        "18.6-trixie"
			digest:     ""
		}
		auth: {
			// -- PostgreSQL database name
			database: "mhq-oss"
			// -- PostgreSQL username
			username: "middleware"
			// -- PostgreSQL password (auto-generated if empty)
			password: ""
		}
		resources: {
			requests: {
				cpu:    "250m"
				memory: "512Mi"
			}
			limits: {
				cpu:    "500m"
				memory: "1Gi"
			}
		}
		podSecurityContext: {
			fsGroup:             999
			fsGroupChangePolicy: "OnRootMismatch"
			seccompProfile: type: "RuntimeDefault"
		}
		securityContext: {
			allowPrivilegeEscalation: false
			capabilities: drop: [
				"ALL",
			]
			readOnlyRootFilesystem: false
			runAsGroup:             999
			runAsNonRoot:           true
			runAsUser:              999
		}
		persistence: {
			size:         "8Gi"
			storageClass: ""
			accessModes: [
				"ReadWriteOnce",
			]
		}
	}

	// =============================================================================
	// Redis Subchart
	// =============================================================================

	redis: {
		// -- Enable bundled Redis
		enabled: true
		// -- Redis container image
		image: {
			repository: "docker.io/valkey/valkey"
			tag:        "9.2"
			digest:     ""
		}
		// -- Redis architecture
		architecture: "standalone"
		resources: {
			requests: {
				cpu:    "100m"
				memory: "128Mi"
			}
			limits: {
				cpu:    "250m"
				memory: "256Mi"
			}
		}
		podSecurityContext: {
			fsGroup:             999
			fsGroupChangePolicy: "OnRootMismatch"
			seccompProfile: type: "RuntimeDefault"
		}
		securityContext: {
			allowPrivilegeEscalation: false
			capabilities: drop: [
				"ALL",
			]
			readOnlyRootFilesystem: false
			runAsGroup:             999
			runAsNonRoot:           true
			runAsUser:              999
		}
		automountServiceAccountToken: false
		persistence: {
			size:         "8Gi"
			storageClass: ""
			accessModes: [
				"ReadWriteOnce",
			]
		}
	}
}
