// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.
// Reference: https://github.com/helmforgedev/charts/blob/main/charts/ghost/values.yaml

@if(!debug)

package main

values: {
	nameOverride:     ""
	fullnameOverride: ""
	commonLabels: {}

	image: {
		repository: "docker.io/library/ghost"
		tag:        "6.62.0"
		pullPolicy: "IfNotPresent"
	}
	imagePullSecrets: []

	ghost: {
		url:      "http://localhost:8080"
		extraEnv: []
	}

	database: external: {
		host:                     ""
		port:                     "3306"
		name:                     "ghost"
		username:                 "ghost"
		password:                 ""
		existingSecret:           ""
		existingSecretPasswordKey: "password"
	}

	persistence: {
		enabled:       true
		size:          "10Gi"
		storageClass:  ""
		accessModes: ["ReadWriteOnce"]
		existingClaim: ""
	}

	backup: {
		enabled:                    false
		schedule:                   "0 3 * * *"
		suspend:                    false
		concurrencyPolicy:          "Forbid"
		successfulJobsHistoryLimit: 3
		failedJobsHistoryLimit:     3
		backoffLimit:               1
		archivePrefix:              "ghost"
		images: {
			backup:   "docker.io/library/busybox:1.38"
			uploader: "docker.io/helmforge/mc:1.0.0"
		}
		resources: {}
		s3: {
			endpoint:                  ""
			bucket:                    ""
			prefix:                    "ghost"
			createBucketIfNotExists:   true
			existingSecret:            ""
			existingSecretAccessKeyKey: "access-key"
			existingSecretSecretKeyKey: "secret-key"
			accessKey:                 ""
			secretKey:                 ""
		}
	}

	serviceAccount: {
		create:                       true
		name:                         ""
		annotations:                  {}
		automountServiceAccountToken: false
	}

	service: {
		type:           "ClusterIP"
		port:           80
		annotations: {}
		ipFamilyPolicy: ""
		ipFamilies: []
	}

	probes: {
		startup: {
			enabled:             true
			path:                "/ghost/api/admin/site/"
			initialDelaySeconds: 15
			periodSeconds:       5
			timeoutSeconds:      3
			failureThreshold:    30
		}
		liveness: {
			enabled:             true
			path:                "/ghost/api/admin/site/"
			initialDelaySeconds: 0
			periodSeconds:       15
			timeoutSeconds:      5
			failureThreshold:    3
		}
		readiness: {
			enabled:             true
			path:                "/ghost/api/admin/site/"
			initialDelaySeconds: 0
			periodSeconds:       10
			timeoutSeconds:      5
			failureThreshold:    3
		}
	}

	resources: {
		requests: {
			cpu:    "100m"
			memory: "256Mi"
		}
		limits: {
			cpu:    "500m"
			memory: "768Mi"
		}
	}

	podSecurityContext: {
		seccompProfile: type: "RuntimeDefault"
		runAsUser:    10001
		runAsGroup:   10001
		fsGroup:      10001
	}
	securityContext: {
		readOnlyRootFilesystem:   true
		allowPrivilegeEscalation: false
		privileged:               false
		runAsNonRoot:             true
		runAsUser:                10001
		runAsGroup:               10001
		capabilities: drop: ["ALL"]
	}

	waitForDatabase: resources: {
		requests: {
			cpu:    "10m"
			memory: "16Mi"
		}
		limits: {
			cpu:    "100m"
			memory: "64Mi"
		}
	}

	nodeSelector: {}
	tolerations: []
	affinity: {}
	topologySpreadConstraints: []
	priorityClassName:             ""
	terminationGracePeriodSeconds: 30

	podLabels: {}
	podAnnotations: {}

	extraVolumes: []
	extraVolumeMounts: []
	extraManifests: []

	mysql: {
		enabled: true
		image: {
			repository: "docker.io/library/mysql"
			tag:        "8.4.10"
			pullPolicy: "IfNotPresent"
		}
		architecture: "standalone"
		auth: {
			database: "ghost"
			username: "ghost"
			password: "mysql_password"
		}
		standalone: {
			persistence: {
				enabled: true
				size:    "8Gi"
			}
			resources: {
				requests: {
					cpu:    "100m"
					memory: "256Mi"
				}
				limits: {
					cpu:    "500m"
					memory: "768Mi"
				}
			}
		}
	}

	ingress: {
		enabled:          false
		ingressClassName: "traefik"
		annotations: {}
		hosts: []
		tls: []
	}

	gateway: {
		enabled:     true
		annotations: {}
		parentRefs: []
		hostnames: []
		path:     "/"
		pathType: "PathPrefix"
	}

	// Render ExternalSecret for the Ghost database password Secret.
    // Requires database.external.existingSecret to be set to prevent credential drift
    // between the chart-managed Secret and the ExternalSecret.

	externalSecrets: {
		enabled:         false
		apiVersion:      "external-secrets.io/v1"
		refreshInterval: "0"
		secretStoreRef: {
			name: ""
			kind: "SecretStore"
		}
		target: creationPolicy: "Owner"
		data: []
	}

}