// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.
// Reference: https://github.com/helmforgedev/charts/blob/main/charts/matomo/values.yaml

@if(!debug)

package main

// All values must be concrete for timoni.
values: {
    nameOverride: ""
    fullnameOverride: ""
    namespaceOverride: ""
    clusterDomain:     "cluster.local"
    commonLabels:      {}
    replicaCount:      1
    image: {
        repository: "docker.io/library/matomo"
        tag: "5.13.0-apache"
        pullPolicy: "IfNotPresent"
    }
    imagePullSecrets: []

    matomo: {
        siteUrl: ""
        trustedHost: ""
        extraEnv: []
        extraEnvFrom: []
    }

    database: {
        mode: "auto" // Database mode could be : auto | external | mysql
        waitForConnection: {
            enabled: true
        }
        external: {
            host: ""
            port: 3306
            name: "matomo"
            username: "matomo"
            password: ""
            existingSecret: ""
            existingSecretPasswordKey: "database-password"
        }
    }

    mysql: {
        enabled: true
        architecture: "standalone"
        image: {
            registry: "docker.io"
            repository: "library/mysql"
            tag: "9.7"
            pullPolicy: "IfNotPresent"
        }
        auth: {
            database: "matomo"
            username: "matomo"
            password: "matomo_password"
            rootPassword: "matomo_root_password"
        }
        primary: {
            persistence: {
                enabled: true
                size: "8Gi"
            }
            resources: {
                requests: {
                    cpu: "100m"
                    memory: "256Mi"
                }
                limits: {
                    cpu: "500m"
                    memory: "1Gi"
                }
            }
            podSecurityContext: {
                runAsUser: 65510
                runAsGroup: 65510
                fsGroup: 65510
                runAsNonRoot: true
                seccompProfile: {
                    type: "RuntimeDefault"
                }
            }
            securityContext: {
                allowPrivilegeEscalation: false
                runAsNonRoot: true
                readOnlyRootFilesystem: false
                capabilities: {
                    drop: [
                        "ALL",
                    ]
                    add: [
                        "NET_BIND_SERVICE",
                    ]
                }
            }
        }
    }

    persistence: {
        enabled: true
        storageClass: ""
        accessMode: "ReadWriteOnce"
        size: "10Gi"
        existingClaim: ""
        annotations: {}
    }

    archiver: {
        enabled: true
        schedule: "5 * * * *"
        concurrencyPolicy: "Forbid"
        successfulJobsHistoryLimit: 3
        failedJobsHistoryLimit: 3
        activeDeadlineSeconds: 7200
        extraArgs: []
        resources: {
            requests: {
                cpu: "100m"
                memory: "256Mi"
            }
            limits: {
                memory: "1Gi"
            }
        }
    }

    php: {
        ini: """
          memory_limit = 256M
          max_execution_time = 180
          upload_max_filesize = 64M
          post_max_size = 64M
          opcache.enable = 1
          opcache.memory_consumption = 128
          """
    }

    service: {
        type: "ClusterIP"
        port: 80
        annotations: {}
        ipFamilyPolicy: ""
        ipFamilies: []
    }

    ingress: {
        enabled: false
        ingressClassName: ""
        annotations: {}
        hosts: []
        tls: []
    }

    gatewayAPI: {
        enabled: false
        httpRoutes: []
    }

    externalSecrets: {
        enabled: false
        refreshInterval: "1h"
        items: []
    }

    metrics: {
        serviceMonitor: {
            enabled: false
            interval: "30s"
            scrapeTimeout: "10s"
            labels: {}
            namespaceSelector: {}
        }
    }

    networkPolicy: {
        enabled: true
        ingressFrom: []
        egress: {
            enabled: false
            allowDNS: true
            extraTo: []
            extraEgress: []
        }
    }

    podDisruptionBudget: {
        enabled: true
        maxUnavailable: 1
        minAvailable: ""
    }

    serviceAccount: {
        create: true
        name: ""
        annotations: {}
        automountServiceAccountToken: false
    }

    apache: {
        port: 8080
    }

    podSecurityContext: {
        runAsUser:  33
        runAsGroup: 33
        fsGroup:    33
        runAsNonRoot: true
        seccompProfile: {
            type: "RuntimeDefault"
        }
    }
    securityContext: {
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        readOnlyRootFilesystem: false
        capabilities: {
            drop: [
                "ALL",
            ]
        }
    }

    startupProbe: {
        enabled: true
        path: "/matomo.php"
        initialDelaySeconds: 20
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 30
    }
    livenessProbe: {
        enabled: true
        path: "/matomo.php"
        initialDelaySeconds: 0
        periodSeconds: 20
        timeoutSeconds: 5
        failureThreshold: 6
    }
    readinessProbe: {
        enabled: true
        path: "/matomo.php"
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 6
    }

    resources: {
        requests: {
            cpu: "100m"
            memory: "256Mi"
        }
        limits: {
            memory: "1Gi"
        }
    }

    terminationGracePeriodSeconds: 30
    updateStrategy: {
        type: "RollingUpdate"
    }

    podLabels: {}
    podAnnotations: {}
    priorityClassName: ""
    nodeSelector: {}
    tolerations: []
    affinity: {}
    topologySpreadConstraints: []

    extraInitContainers: []
    extraContainers: []
    extraVolumes: []
    extraVolumeMounts: []
    extraManifests: []
}
