// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.
// Reference: https://github.com/helmforgedev/charts/blob/main/charts/uptime-kuma/values.yaml

@if(!debug)

package main

// Default values for uptime-kuma mirroring Helm chart values.yaml.
values: {
	// =============================================================================
	// Uptime Kuma Helm Chart - Default Values
	// =============================================================================
	// Focus: self-hosted monitoring with SQLite or MariaDB, status pages, notifications

	nameOverride:     ""
	fullnameOverride: ""
	commonLabels: {}

	// =============================================================================
	// Image
	// =============================================================================

	image: {
		// Uptime Kuma container image
		repository: "docker.io/louislam/uptime-kuma"
		// Image tag
		tag:        "2.5.5"
		digest:     ""
		pullPolicy: "IfNotPresent"
	}

	imagePullSecrets: []

	// =============================================================================
	// Uptime Kuma Configuration
	// =============================================================================

	uptimeKuma: {
		// Application port
		port: 3001
		// Allow iframe embedding from different origins
		disableFrameSameOrigin: false
		// Extra environment variables for the container
		extraEnv: []
	}

	// =============================================================================
	// Database
	// =============================================================================

	database: {
		// Database type: sqlite or mariadb
		type: "mariadb"
		// External MariaDB configuration (used when mysql subchart is disabled and type is mariadb)
		external: {
			host:     ""
			port:     "3306"
			name:     "uptime_kuma"
			username: "uptime_kuma"
			password: ""
			// Existing secret containing the database password
			existingSecret: ""
			// Key in the existing secret containing the password
			existingSecretPasswordKey: "password"
		}
	}

	// =============================================================================
	// Persistence
	// =============================================================================

	persistence: {
		// Enable persistence for /app/data (SQLite DB, config, certificates)
		enabled: true
		// Storage size
		size: "2Gi"
		// Storage class
		storageClass: ""
		// Access modes
		accessModes: [
			"ReadWriteOnce",
		]
		// Use an existing PVC
		existingClaim: ""
	}

	// =============================================================================
	// Service Account
	// =============================================================================

	serviceAccount: {
		// Create a ServiceAccount
		create: true
		// ServiceAccount name
		name: ""
		// Annotations for the ServiceAccount
		annotations: {}
		// Automount API credentials for a Service Account
		automountServiceAccountToken: false
	}

	// =============================================================================
	// Service
	// =============================================================================

	service: {
		// Service type
		type: "ClusterIP"
		// HTTP service port
		port: 80
		// Annotations for the Service
		annotations: {}
	}


	// =============================================================================
	// Probes
	// =============================================================================

	probes: {
		startup: {
			enabled:             true
			path:                "/"
			initialDelaySeconds: 10
			periodSeconds:       5
			timeoutSeconds:      3
			failureThreshold:    30
		}
		liveness: {
			enabled:             true
			path:                "/"
			initialDelaySeconds: 0
			periodSeconds:       15
			timeoutSeconds:      5
			failureThreshold:    3
		}
		readiness: {
			enabled:             true
			path:                "/"
			initialDelaySeconds: 0
			periodSeconds:       10
			timeoutSeconds:      5
			failureThreshold:    3
		}
	}

	// =============================================================================
	// Resources and Security
	// =============================================================================

	resources: {
		requests: {
			cpu:    "100m"
			memory: "128Mi"
		}
		limits: {
			cpu:    "500m"
			memory: "512Mi"
		}
	}

	podSecurityContext: {
		fsGroup:             10001
		fsGroupChangePolicy: "OnRootMismatch"
		seccompProfile: {
			type: "RuntimeDefault"
		}
	}

	securityContext: {
		allowPrivilegeEscalation: false
		capabilities: {
			drop: [
				"ALL",
			]
		}
		readOnlyRootFilesystem: false
		runAsNonRoot:           true
		runAsUser:              65510
		runAsGroup:             65510
	}

	// Container lifecycle hooks. The default preStop gives Kubernetes time to
	// drain the terminating pod before Uptime Kuma exits, avoiding transient
	// readiness probe warnings during rollouts.
	lifecycle: {
		preStop: {
			exec: {
				command: [
					"sh",
					"-c",
					"sleep 5",
				]
			}
		}
	}

	// =============================================================================
	// Scheduling
	// =============================================================================

	nodeSelector: {}
	tolerations: []
	affinity: {}
	topologySpreadConstraints: []
	priorityClassName:             ""
	terminationGracePeriodSeconds: 30

	podLabels: {}
	podAnnotations: {}

	// =============================================================================
	// Backup
	// =============================================================================

	backup: {
		// Enable built-in backup CronJob (SQLite tar or mysqldump + S3 upload)
		enabled: false
		// Backup schedule in Cron format
		schedule: "0 2 * * *"
		// Suspend backup execution
		suspend: false
		// CronJob concurrency policy
		concurrencyPolicy: "Forbid"
		// Successful job history retained
		successfulJobsHistoryLimit: 3
		// Failed job history retained
		failedJobsHistoryLimit: 3
		// Job backoff limit
		backoffLimit: 1
		// Prefix for backup archive names
		archivePrefix: "uptime-kuma"
		// Resources for backup containers
		resources: {}
		images: {
			uploader: {
				repository: "docker.io/helmforge/mc"
				tag:        "1.0.0"
				digest:     ""
				pullPolicy: "IfNotPresent"
			}
			mysql: {
				repository: "docker.io/library/mysql"
				tag:        "8.4"
				digest:     ""
				pullPolicy: "IfNotPresent"
			}
		}
		s3: {
			// S3-compatible endpoint URL
			endpoint: ""
			// Target bucket name
			bucket: ""
			// Optional prefix inside the bucket
			prefix: "uptime-kuma"
			// Create bucket if not exists
			createBucketIfNotExists: true
			// Existing secret containing access-key and secret-key
			existingSecret:             ""
			existingSecretAccessKeyKey: "access-key"
			existingSecretSecretKeyKey: "secret-key"
			// Inline access key
			accessKey: ""
			// Inline secret key
			secretKey: ""
		}
	}

	// =============================================================================
	// Extra
	// =============================================================================

	extraVolumes: []
	extraVolumeMounts: []

	// Extra manifests to deploy alongside the chart
	extraManifests: []

	// =============================================================================
	// Gateway API
	// =============================================================================

	// -- Gateway.
	gatewayAPI: {
		// -- Render canonical Gateway API HTTPRoutes.
		enabled: false
		// -- GatewayClass name.
		gatewayClassName: ""
		// -- Route definitions with parentRefs, hostnames, rules, labels and annotations.
		httpRoutes: [
			{
				name: ""
				// -- Route labels.
				labels: {}
				// -- Route annotations.
				annotations: {}
				// -- References to parent Gateways.
				parentRefs: [
					{
						// -- Gateway name.
						name: "gateway"
						// -- Gateway namespace (optional, defaults to route namespace).
						namespace: ""
						// -- Gateway API group.
						group: "gateway.networking.k8s.io"
						// -- Gateway API kind.
						kind: "Gateway"
						// -- Gateway section name.
						sectionName: ""
						// -- Gateway listener port.
						port: 80
					},
				]
				// -- Hostnames matching the route.
				hostnames: []
				// -- Routing rules, match conditions, filters and backend references.
				rules: [
					{
						matches: [
							{
								path: {
									type:  "PathPrefix"
									value: "/"
								}
							},
						]
					},
				]
			},
		]
	}

	// =============================================================================
	// External Secrets
	// =============================================================================

	externalSecrets: {
		// Render ExternalSecret resources for database, backup, or integration credentials
		enabled: false
		// ExternalSecret API version
		apiVersion: "external-secrets.io/v1"
		// Default provider sync interval for ExternalSecret items that do not set spec.refreshInterval
		refreshInterval: "1h"
		// ExternalSecret definitions. Each item requires a full `spec`.
		items: []
	}

	// =============================================================================
	// Subcharts
	// =============================================================================

	mysql: {
		// Enable the local MySQL chart (used as MariaDB-compatible backend)
		enabled:      true
		architecture: "standalone"
		image: {
			// MySQL container image
			repository: "docker.io/library/mysql"
			// Image tag
			tag:        "9.7.2"
			digest:     ""
			pullPolicy: "IfNotPresent"
		}
		auth: {
			database: "uptime_kuma"
			username: "uptime_kuma"
			password: "mysql_password"
		}
		resources: {
			requests: {
				cpu:    "250m"
				memory: "512Mi"
			}
			limits: {
				cpu:    "500m"
				memory: "1Gi"
			}
		}
	}
}
