// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.
// Reference: https://github.com/suitenumerique/docs/blob/main/documentation/installation/kubernetes.md

@if(!debug)

package main

// Defaults
values: {
	image: {
		repository: "lasuite/impress-backend"
		pullPolicy: "Always"
		tag:        "v5.4.1"
	}

	nameOverride:     ""
	fullnameOverride: ""

	djangoSecretKey:      "lkjsdlfkjsldkfjslkdfjslkdjfslkdjf"
	djangoSuperUserEmail: "admin@example.com"
	djangoSuperUserPass:  "admin"
	aiApiKey:             "changeme"
	aiBaseUrl:            "changeme"
	oidc: {
		clientId:     "impress"
		clientSecret: "ThisIsAnExampleKeyForDevPurposeOnly"
	}

	// Common environment variables reused across all components
	let _commonEnvVars = {
		COLLABORATION_SERVER_SECRET: "my-secret"
		DJANGO_CSRF_TRUSTED_ORIGINS: "https://docs.127.0.0.1.nip.io,http://docs.127.0.0.1.nip.io"
		DJANGO_CONFIGURATION:        "Feature"
		DJANGO_ALLOWED_HOSTS:        "docs.127.0.0.1.nip.io"
		DJANGO_SERVER_TO_SERVER_API_TOKENS: "secret-api-key"
		DJANGO_SECRET_KEY:           "lkjsdlfkjsldkfjslkdfjslkdjfslkdjf"
		DJANGO_SETTINGS_MODULE:      "impress.settings"
		DJANGO_SUPERUSER_PASSWORD:     "admin"
		DJANGO_SUPERUSER_EMAIL:        "admin@example.com"
		DJANGO_EMAIL_BRAND_NAME:      "La Suite Numérique"
		DJANGO_EMAIL_HOST:            "mailcatcher"
		DJANGO_EMAIL_LOGO_IMG:        "https://docs.127.0.0.1.nip.io/assets/logo-suite-numerique.png"
		DJANGO_EMAIL_PORT:            "1025"
		DJANGO_EMAIL_URL_APP:         "https://docs.127.0.0.1.nip.io"
		DJANGO_EMAIL_USE_SSL:         "False"
		LOGGING_LEVEL_HANDLERS_CONSOLE: "ERROR"
		LOGGING_LEVEL_LOGGERS_ROOT:   "INFO"
		LOGGING_LEVEL_LOGGERS_APP:    "INFO"
		OIDC_USERINFO_SHORTNAME_FIELD: "given_name"
		OIDC_USERINFO_FULLNAME_FIELDS: "given_name,usual_name"
		OIDC_OP_JWKS_ENDPOINT:         "https://keycloak.127.0.0.1.nip.io/realms/docs/protocol/openid-connect/certs"
		OIDC_OP_AUTHORIZATION_ENDPOINT: "https://keycloak.127.0.0.1.nip.io/realms/docs/protocol/openid-connect/auth"
		OIDC_OP_TOKEN_ENDPOINT:         "https://keycloak.127.0.0.1.nip.io/realms/docs/protocol/openid-connect/token"
		OIDC_OP_USER_ENDPOINT:          "https://keycloak.127.0.0.1.nip.io/realms/docs/protocol/openid-connect/userinfo"
		OIDC_OP_LOGOUT_ENDPOINT:        "https://keycloak.127.0.0.1.nip.io/realms/docs/protocol/openid-connect/logout"
		OIDC_RP_CLIENT_ID:              "docs"
		OIDC_RP_CLIENT_SECRET:          "ThisIsAnExampleKeyForDevPurposeOnly"
		OIDC_RP_SIGN_ALGO:              "RS256"
		OIDC_RP_SCOPES:                 "openid email"
		OIDC_REDIRECT_ALLOWED_HOSTS:    "https://docs.127.0.0.1.nip.io"
		OIDC_VERIFY_SSL:                "False"
		LOGIN_REDIRECT_URL:             "https://docs.127.0.0.1.nip.io"
		LOGIN_REDIRECT_URL_FAILURE:     "https://docs.127.0.0.1.nip.io"
		LOGOUT_REDIRECT_URL:            "https://docs.127.0.0.1.nip.io"
		DB_HOST:                        "postgres"
		DB_NAME:                        "docs"
		DB_USER:                        "dinum"
		DB_PASSWORD:                    "pass"
		DB_PORT:                        "5432"
		REDIS_URL:                      "redis://default:pass@redis-master:6379/1"
		DJANGO_CELERY_BROKER_URL:      "redis://default:pass@redis-master:6379/1"
		AWS_STORAGE_BUCKET_NAME:       "docs-media-storage"
		AWS_S3_ENDPOINT_URL:           "http://docs-minio:9000/"
		AWS_S3_ACCESS_KEY_ID:           "dinum"
		AWS_S3_SECRET_ACCESS_KEY:       "password"
		AWS_S3_SECURE_ACCESS:           "False"
		STORAGES_STATICFILES_BACKEND:   "django.contrib.staticfiles.storage.StaticFilesStorage"
		USER_RECONCILIATION_FORM_URL:   "https://docs.127.0.0.1.nip.io"
		Y_PROVIDER_API_BASE_URL:        "http://docs-y-provider:4444/api/"
		Y_PROVIDER_API_KEY:             "my-secret"
		CACHES_KEY_PREFIX:              "docs"
	}

	commonEnvVars: {}

	ingress: {
		enabled:   true
		className: "nginx"
		host:      "docs.127.0.0.1.nip.io"
		path:      "/"
		hosts:     []
		tls: {
			secretName: null
			enabled:    true
			additional: []
		}
		customBackends: []
	}

	ingressCollaborationWS: {
		enabled:   true
		className: "nginx"
		host:      "docs.127.0.0.1.nip.io"
		path:      "/collaboration/ws/"
		hosts:     []
		tls: {
			secretName: null
			enabled:    true
			additional: []
		}
		customBackends: []
		annotations: {
			"nginx.ingress.kubernetes.io/enable-websocket": "true"
			"nginx.ingress.kubernetes.io/proxy-read-timeout": "86400"
			"nginx.ingress.kubernetes.io/proxy-send-timeout": "86400"
			"nginx.ingress.kubernetes.io/upstream-hash-by": "$arg_room"
		}
	}

	ingressRedirects: {
		enabled:   false
		className: null
		host:      "impress.example.com"
		tls: {
			enabled:    true
			secretName: null
			additional: []
		}
		rules: []
	}

	ingressCollaborationApi: {
		enabled:   true
		className: "nginx"
		host:      "docs.127.0.0.1.nip.io"
		path:      "/collaboration/api/"
		hosts:     []
		tls: {
			secretName: null
			enabled:    true
			additional: []
		}
		customBackends: []
		annotations: {
			"nginx.ingress.kubernetes.io/upstream-hash-by": "$arg_room"
		}
	}

	ingressAdmin: {
		enabled:   true
		className: "nginx"
		host:      "docs.127.0.0.1.nip.io"
		path:      "/admin"
		hosts:     []
		tls: {
			secretName: null
			enabled:    true
			additional: []
		}
	}

	ingressMedia: {
		enabled:   true
		className: "nginx"
		host:      "docs.127.0.0.1.nip.io"
		path:      "/media/(.*)"
		hosts:     []
		tls: {
			secretName: null
			enabled:    true
			additional: []
		}
		annotations: {
			"nginx.ingress.kubernetes.io/auth-url":              "https://docs.127.0.0.1.nip.io/api/v1.0/documents/media-auth/"
			"nginx.ingress.kubernetes.io/auth-response-headers": "Authorization, X-Amz-Date, X-Amz-Content-SHA256"
			"nginx.ingress.kubernetes.io/upstream-vhost":        "minio-dev-backend-minio.impress.svc.cluster.local:9000"
			"nginx.ingress.kubernetes.io/rewrite-target":        "/docs-media-storage/$1"
		}
	}

	serviceMedia: {
		host:        "docs-minio.docs.svc.cluster.local"
		port:        9000
		annotations: {}
	}

	backend: {
		command: []
		args:    []
		replicas: 1
		resources: {
			limits: {
				cpu:    "1000m"
				memory: "1024Mi"
			}
			requests: {
				cpu:    "100m"
				memory: "256Mi"
			}
		}
		shareProcessNamespace: false
		sidecars: []
		migrateJobAnnotations: {}
		jobs: {
			ttlSecondsAfterFinished: 30
			backoffLimit:            2
		}
		securityContext: {
			allowPrivilegeEscalation: false
			readOnlyRootFilesystem:   true
			runAsNonRoot:             true
			runAsUser:                65510
			runAsGroup:               65510
			capabilities: drop: ["ALL"]
			seccompProfile: type: "RuntimeDefault"
		}
		podSecurityContext: {
			runAsNonRoot: true
			runAsUser:    65510
			runAsGroup:   65510
			fsGroup:      65510
			seccompProfile: type: "RuntimeDefault"
		}
		envVars: _commonEnvVars
		envFrom: []
		django: {
			envVars: {}
			envFrom: []
		}
		podAnnotations: {}
		dpAnnotations:  {}
		service: {
			type:       "ClusterIP"
			port:       80
			targetPort: 8000
			annotations: {}
		}
		migrate: {
			command: [
				"/bin/sh",
				"-c",
				"""
				while ! python manage.py check --database default > /dev/null 2>&1
				do
				  echo "Database not ready"
				  sleep 2
				done
				echo "Database is ready"
				python manage.py migrate --no-input
				""",
			]
			restartPolicy: "Never"
		}
		createsuperuser: {
			command: [
				"/bin/sh",
				"-c",
				"""
				while ! python manage.py check --database default > /dev/null 2>&1
				do
				  echo "Database not ready"
				  sleep 2
				done
				echo "Database is ready"
				python manage.py createsuperuser --email admin@example.com --password admin
				""",
			]
			restartPolicy: "Never"
		}
		job: {
			name:          ""
			command:       []
			restartPolicy: "Never"
			annotations: {
				"argocd.argoproj.io/hook": "PostSync"
			}
		}
		cronjobs: []
		probes: {
			liveness: {
				path:                "/__lbheartbeat__"
				initialDelaySeconds: 10
			}
			readiness: {
				path:                "/__heartbeat__"
				initialDelaySeconds: 10
			}
		}
		resources: {}
		nodeSelector: {}
		tolerations: []
		affinity: {}
		persistence: {}
		extraVolumeMounts: [
			{
				name:      "certs"
				mountPath: "/cert/cacert.pem"
				subPath:   "cacert.pem"
			},
		]
		extraVolumes: [
			{
				name: "certs"
				configMap: {
					name: "certifi"
					items: [
						{
							key:  "cacert.pem"
							path: "cacert.pem"
						},
					]
				}
			},
		]
		pdb: enabled: true
		serviceAccountName:           "default"
		automountServiceAccountToken: false
		themeCustomization: {
			enabled: false
			file_content: "{}"
			mount_path: "/app/impress/configuration/theme"
		}
		celery: {
			replicas: 1
			command: []
			args: [
				"celery",
				"-A",
				"impress.celery_app",
				"worker",
				"-l",
				"INFO",
				"-n",
				"impress@%h",
			]
			envVars: _commonEnvVars
			envFrom: []
			resources: {
				limits: {
					cpu:    "1000m"
					memory: "1536Mi"
				}
				requests: {
					cpu:    "100m"
					memory: "256Mi"
				}
			}
			probes: {
				liveness: {
					exec: command: [
						"/bin/sh",
						"-c",
						"celery -A impress.celery_app inspect ping -d impress@$HOSTNAME",
					]
					initialDelaySeconds: 60
					timeoutSeconds:      15
				}
				readiness: {
					exec: command: [
						"/bin/sh",
						"-c",
						"celery -A impress.celery_app inspect ping -d impress@$HOSTNAME",
					]
					initialDelaySeconds: 60
					timeoutSeconds:      15
				}
			}
			automountServiceAccountToken: false
			serviceAccountName:           "default"
			securityContext: {
				allowPrivilegeEscalation: false
				readOnlyRootFilesystem:   true
				runAsNonRoot:             true
				runAsUser:                65510
				runAsGroup:               65510
				capabilities: drop: ["ALL"]
				seccompProfile: type: "RuntimeDefault"
			}
			podSecurityContext: {
				runAsNonRoot: true
				runAsUser:    65510
				runAsGroup:   65510
				fsGroup:      65510
				seccompProfile: type: "RuntimeDefault"
			}
		}
	}

	frontend: {
		image: {
			repository: "lasuite/impress-frontend"
			pullPolicy: "Always"
			tag:        "v5.4.1"
		}
		command: []
		args:    []
		replicas: 1
		resources: {
			limits: {
				cpu:    "500m"
				memory: "512Mi"
			}
			requests: {
				cpu:    "100m"
				memory: "128Mi"
			}
		}
		shareProcessNamespace: false
		sidecars: []
		securityContext: {
			allowPrivilegeEscalation: false
			readOnlyRootFilesystem:   true
			runAsNonRoot:             true
			runAsUser:                65510
			runAsGroup:               65510
			capabilities: drop: ["ALL"]
			seccompProfile: type: "RuntimeDefault"
		}
		podSecurityContext: {
			runAsNonRoot: true
			runAsUser:    65510
			runAsGroup:   65510
			fsGroup:      65510
			seccompProfile: type: "RuntimeDefault"
		}
		envVars: _commonEnvVars
		envFrom: []
		podAnnotations: {}
		dpAnnotations:  {}
		service: {
			type:       "ClusterIP"
			port:       80
			targetPort: 8080
			annotations: {}
		}
		probes: {}
		resources: {}
		nodeSelector: {}
		tolerations: []
		affinity: {}
		persistence: {}
		extraVolumeMounts: []
		extraVolumes: []
		pdb: enabled: true
		serviceAccountName:           "default"
		automountServiceAccountToken: false
	}

	posthog: {
		ingress: {
			enabled:   false
			className: "nginx"
			host:      "docs.127.0.0.1.nip.io"
			path:      "/"
			hosts:     []
			tls: {
				enabled:    true
				additional: []
			}
			customBackends: []
			annotations: {}
		}
		ingressAssets: {
			enabled:   false
			className: "nginx"
			host:      "docs.127.0.0.1.nip.io"
			path:      "/"
			hosts:     []
			tls: {
				enabled:    true
				additional: []
			}
			customBackends: []
			annotations: {}
		}
		service: {
			type:         "ExternalName"
			port:         443
			externalName: "eu.i.posthog.com"
			annotations: {}
		}
		assetsService: {
			type:         "ExternalName"
			port:         443
			externalName: "eu-assets.i.posthog.com"
			annotations: {}
		}
	}

	yProvider: {
		image: {
			repository: "lasuite/impress-y-provider"
			pullPolicy: "Always"
			tag:        "v5.4.1"
		}
		converter: {
			enabled: false
			replicas: 3
			resources: {}
			service: {}
			pdb: enabled: false
		}
		command: []
		args: []
		shareProcessNamespace: false
		resources: {
			limits: {
				cpu:    "1000m"
				memory: "1024Mi"
			}
			requests: {
				cpu:    "100m"
				memory: "256Mi"
			}
		}
		sidecars: []
		securityContext: {
			allowPrivilegeEscalation: false
			readOnlyRootFilesystem:   true
			runAsNonRoot:             true
			runAsUser:                65510
			runAsGroup:               65510
			capabilities: drop: ["ALL"]
			seccompProfile: type: "RuntimeDefault"
		}
		podSecurityContext: {
			runAsNonRoot: true
			runAsUser:    65510
			runAsGroup:   65510
			fsGroup:      65510
			seccompProfile: type: "RuntimeDefault"
		}
		envVars: {
			COLLABORATION_BACKEND_BASE_URL: "https://docs.127.0.0.1.nip.io"
			COLLABORATION_LOGGING:          "true"
			COLLABORATION_SERVER_ORIGIN:    "https://docs.127.0.0.1.nip.io"
			COLLABORATION_SERVER_SECRET:    "my-secret"
			Y_PROVIDER_API_KEY:             "my-secret"
		}
		envFrom: []
		podAnnotations: {}
		dpAnnotations: {}
		service: {
			type:       "ClusterIP"
			port:       4444
			targetPort: 4444
			annotations: {}
		}
		probes: {
			liveness: {
				path:                "/healthz"
				initialDelaySeconds: 60
				periodSeconds:       10
			}
			readiness: {
				path:                "/healthz"
				initialDelaySeconds: 60
				periodSeconds:       10
			}
		}
		resources: {}
		nodeSelector: {}
		tolerations: []
		affinity: {}
		persistence: {}
		extraVolumeMounts: []
		extraVolumes: []
		pdb: enabled: true
		serviceAccountName:           "default"
		automountServiceAccountToken: false
	}

	postgresql: {
		enabled: true
		image: {
			repository: "postgres"
			tag:        "18-alpine"
			digest:     ""
			pullPolicy: "IfNotPresent"
		}
		host:     "postgres"
		database: "docs"
		username: "dinum"
		password: "pass"
	}

	kc_postgresql: {
		enabled: true
		image: {
			repository: "postgres"
			tag:        "16-alpine"
			digest:     ""
			pullPolicy: "IfNotPresent"
		}
		host:     "kc-postgres"
		database: "keycloak"
		username: "keycloak"
		password: "keycloak"
	}

	redis: {
		enabled: true
		image: {
			repository: "redis"
			tag:        "8.8-alpine"
			digest:     ""
			pullPolicy: "IfNotPresent"
		}
	}

	keycloak: {
		enabled:       true
		adminUser:     "admin"
		adminPassword: "pass"
		host:          "keycloak.127.0.0.1.nip.io"
		image: {
			repository: "quay.io/keycloak/keycloak"
			tag:        "20.0.1"
			digest:     ""
			pullPolicy: "IfNotPresent"
		}
		ingress: {
			enabled:   true
			className: "nginx"
			// TEST: annotations commented out to verify stale cookies (not buffer size)
			// were the real cause of "Network is unavailable" on login.
			// Uncomment if 502 errors reappear in nginx logs.
			// annotations: {
			// 	"nginx.ingress.kubernetes.io/proxy-buffer-size":       "128k"
			// 	"nginx.ingress.kubernetes.io/proxy-buffers":            "4 256k"
			// 	"nginx.ingress.kubernetes.io/proxy-busy-buffers-size": "256k"
			// }
		}
		db: {
			host:     "kc-postgres"
			database: "keycloak"
			username: "keycloak"
			password: "keycloak"
			schema:   "public"
		}
		realmJson: """
			{
			  "realm": "docs",
			  "enabled": true,
			  "clients": [
			    {
			      "clientId": "docs",
			      "enabled": true,
			      "publicClient": false,
			      "secret": "ThisIsAnExampleKeyForDevPurposeOnly",
			      "redirectUris": [
			        "https://docs.127.0.0.1.nip.io/*",
			        "http://docs.127.0.0.1.nip.io/*"
			      ],
			      "webOrigins": [
			        "https://docs.127.0.0.1.nip.io",
			        "http://docs.127.0.0.1.nip.io"
			      ]
			    }
			  ]
			}
			"""
	}

	minio: {
		enabled: true
		image: {
			repository: "minio/minio"
			tag:        "RELEASE.2023-08-29T23-07-35Z"
			digest:     ""
			pullPolicy: "IfNotPresent"
		}
		mcImage: {
			repository: "minio/mc"
			tag:        "RELEASE.2025-08-13T08-35-41Z-cpuv1"
			digest:     ""
			pullPolicy: "IfNotPresent"
		}
		caCert:       ""
		ingress: {
			enabled:    true
			className:  "nginx"
			host:       "minio.127.0.0.1.nip.io"
		}
	}

	docSpec: {
		enabled: false
		image: {
			repository: "ghcr.io/docspecio/api"
			tag:        "3.0.1"
			pullPolicy: "IfNotPresent"
		}
		command: []
		args: []
		replicas: 1
		securityContext: {
			allowPrivilegeEscalation: false
			readOnlyRootFilesystem:   true
			runAsNonRoot:             true
			runAsUser:                65510
			runAsGroup:               65510
			capabilities: drop: ["ALL"]
			seccompProfile: type: "RuntimeDefault"
		}
		podSecurityContext: {
			runAsNonRoot: true
			runAsUser:    65510
			runAsGroup:   65510
			fsGroup:      65510
			seccompProfile: type: "RuntimeDefault"
		}
		envVars: {}
		envFrom: []
		service: {
			type:       "ClusterIP"
			port:       4000
			targetPort: 4000
		}
		probes: {
			liveness: path:  "/health"
			readiness: path: "/health"
		}
		resources: {}
		nodeSelector: {}
		tolerations: []
		affinity: {}
		persistence: {}
		extraVolumeMounts: []
		extraVolumes: []
	}



	extraManifests: []
}
