// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.
// Reference: https://github.com/helmforgedev/charts/blob/main/charts/automatisch/values.yaml
// Notes: You can use user@automatisch.io email address and sample password to login to Automatisch. 
// Please do not forget to change your email and password from the settings page.

@if(!debug)

package main

// Defaults
values: {
	nameOverride:     ""
	fullnameOverride: ""
	commonLabels:     {}

	image: {
		repository: "docker.io/automatischio/automatisch"
		tag:        "0.15.0"
		pullPolicy: "IfNotPresent"
	}

	imagePullSecrets: []

	automatisch: {
		webAppUrl: "http://localhost:3000"
		appEnv:    "production"
		extraEnv:  []
	}

	database: {
		external: {
			host:                      ""
			port:                      "5432"
			name:                      "automatisch"
			username:                  "automatisch"
			password:                  ""
			existingSecret:            ""
			existingSecretPasswordKey: "password"
		}
	}

	redis_config: {
		external: {
			host:           ""
			port:           "6379"
			existingSecret: ""
		}
	}

	serviceAccount: {
		create:      true
		name:        ""
		annotations: {}
	}

	service: {
		type:        "ClusterIP"
		port:        80
		annotations: {}
	}

	ingress: {
		enabled:          false
		ingressClassName: "traefik"
		annotations:      {}
		hosts:            []
		tls:              []
	}

	probes: {
		startup: {
			enabled:             true
			initialDelaySeconds: 10
			periodSeconds:       5
			timeoutSeconds:      3
			failureThreshold:    30
		}
		liveness: {
			enabled:             true
			initialDelaySeconds: 0
			periodSeconds:       15
			timeoutSeconds:      5
			failureThreshold:    3
		}
		readiness: {
			enabled:             true
			initialDelaySeconds: 0
			periodSeconds:       10
			timeoutSeconds:      5
			failureThreshold:    3
		}
	}

	resources: {
		requests: {
			cpu:    "100m"
			memory: "128Mi"
		}
		limits: {
			cpu:    "500m"
			memory: "512Mi"
		}
	}
	podSecurityContext: {
		runAsUser:    65510
		runAsGroup:   65510
		runAsNonRoot: true
		fsGroup:      65510
		seccompProfile: {
			type: "RuntimeDefault"
		}
	}
	securityContext: {
		allowPrivilegeEscalation: false
		capabilities: {
			drop: ["ALL"]
		}
		runAsUser:    65510
		runAsGroup:   65510
		runAsNonRoot: true
	}

	nodeSelector:              {}
	tolerations:               []
	affinity:                  {}
	topologySpreadConstraints: []
	priorityClassName:             ""
	terminationGracePeriodSeconds: 30

	podLabels:      {}
	podAnnotations: {}

	extraVolumes: [
		{
			name: "logs"
			emptyDir: {}
		}
	]
	extraVolumeMounts: [
		{
			name:      "logs"
			mountPath: "/automatisch/packages/backend/logs"
		}
	]

	extraManifests: []

	postgresql: {
		enabled:      true
		architecture: "standalone"
		auth: {
			database: "automatisch"
			username: "automatisch"
			password: "change-me-please-db-password!"
		}
		image: {
			repository: "docker.io/library/postgres"
			tag:        "18.6-trixie"
			pullPolicy: "IfNotPresent"
			digest:     ""
		}
		persistence: {
			enabled:      true
			size:         "8Gi"
			storageClass: ""
		}
		resources: {
			requests: {
				cpu:    "100m"
				memory: "256Mi"
			}
			limits: {
				cpu:    "500m"
				memory: "512Mi"
			}
		}
		podSecurityContext: {
			runAsUser:    65510
			runAsGroup:   65510
			runAsNonRoot: true
			fsGroup:      65510
			seccompProfile: {
				type: "RuntimeDefault"
			}
		}
		securityContext: {
			allowPrivilegeEscalation: false
			capabilities: {
				drop: ["ALL"]
			}
			runAsUser:    65510
			runAsGroup:   65510
			runAsNonRoot: true
		}
	}
	redis: {
		enabled:      true
		architecture: "standalone"
		image: {
			repository: "docker.io/library/redis"
			tag:        "8.8.2"
			pullPolicy: "IfNotPresent"
			digest:     ""
		}
		persistence: {
			enabled:      true
			size:         "8Gi"
			storageClass: ""
		}
		resources: {
			requests: {
				cpu:    "50m"
				memory: "64Mi"
			}
			limits: {
				cpu:    "200m"
				memory: "128Mi"
			}
		}
		podSecurityContext: {
			runAsUser:    65510
			runAsGroup:   65510
			runAsNonRoot: true
			fsGroup:      65510
			seccompProfile: {
				type: "RuntimeDefault"
			}
		}
		securityContext: {
			allowPrivilegeEscalation: false
			capabilities: {
				drop: ["ALL"]
			}
			runAsUser:    65510
			runAsGroup:   65510
			runAsNonRoot: true
		}
	}
	// Secret keys required for Automatisch
	// You can use the openssl rand -base64 36 command in your terminal to generate a random string for the 
	// ENCRYPTION_KEY and WEBHOOK_SECRET_KEY environment variables.
	encryptionKey:    "PwUzx9lRxIieaIQenGcpg3NjbL6l91tH46QaWBFS5hjikt3A"
	appSecretKey:     "changemeplease32characterslong!!"
	webhookSecretKey: "OdLnAp2KjCNd+VgpKqf5g72Kts2L1YFJwKzdebVtczL4yrGR"
}
